/* Startdeck Spanisch -> Deutsch.
   Jeder Eintrag: es, de (Alternativen mit |), pos, level, topic, ex (Beispielsatz), exDe */
const DECK = [
  // --- A1: Grundlagen / Personen ---
  { es: "el hombre", de: "der Mann", pos: "noun", level: "A1", topic: "Menschen", ex: "El hombre lee el periódico.", exDe: "Der Mann liest die Zeitung." },
  { es: "la mujer", de: "die Frau", pos: "noun", level: "A1", topic: "Menschen", ex: "La mujer trabaja en un hospital.", exDe: "Die Frau arbeitet in einem Krankenhaus." },
  { es: "el niño", de: "das Kind|der Junge", pos: "noun", level: "A1", topic: "Menschen", ex: "El niño juega en el parque.", exDe: "Das Kind spielt im Park." },
  { es: "el amigo", de: "der Freund", pos: "noun", level: "A1", topic: "Menschen", ex: "Mi amigo vive en Madrid.", exDe: "Mein Freund wohnt in Madrid." },
  { es: "la familia", de: "die Familie", pos: "noun", level: "A1", topic: "Menschen", ex: "Toda la familia come junta los domingos.", exDe: "Die ganze Familie isst sonntags zusammen." },
  { es: "el hermano", de: "der Bruder", pos: "noun", level: "A1", topic: "Menschen", ex: "Mi hermano tiene veinte años.", exDe: "Mein Bruder ist zwanzig Jahre alt." },
  { es: "la hija", de: "die Tochter", pos: "noun", level: "A1", topic: "Menschen", ex: "Su hija estudia medicina.", exDe: "Ihre Tochter studiert Medizin." },
  { es: "el vecino", de: "der Nachbar", pos: "noun", level: "A2", topic: "Menschen", ex: "El vecino siempre saluda por la mañana.", exDe: "Der Nachbar grüßt morgens immer." },

  // --- Alltag / Zuhause ---
  { es: "la casa", de: "das Haus", pos: "noun", level: "A1", topic: "Zuhause", ex: "Nuestra casa está cerca de la playa.", exDe: "Unser Haus ist in der Nähe des Strandes." },
  { es: "la puerta", de: "die Tür", pos: "noun", level: "A1", topic: "Zuhause", ex: "Por favor, cierra la puerta.", exDe: "Bitte schließ die Tür." },
  { es: "la ventana", de: "das Fenster", pos: "noun", level: "A1", topic: "Zuhause", ex: "Abro la ventana porque hace calor.", exDe: "Ich öffne das Fenster, weil es heiß ist." },
  { es: "la mesa", de: "der Tisch", pos: "noun", level: "A1", topic: "Zuhause", ex: "La comida ya está en la mesa.", exDe: "Das Essen steht schon auf dem Tisch." },
  { es: "la silla", de: "der Stuhl", pos: "noun", level: "A1", topic: "Zuhause", ex: "Esta silla es muy cómoda.", exDe: "Dieser Stuhl ist sehr bequem." },
  { es: "la cama", de: "das Bett", pos: "noun", level: "A1", topic: "Zuhause", ex: "Los sábados me quedo en la cama.", exDe: "Samstags bleibe ich im Bett." },
  { es: "la cocina", de: "die Küche", pos: "noun", level: "A1", topic: "Zuhause", ex: "Mi madre está en la cocina.", exDe: "Meine Mutter ist in der Küche." },
  { es: "la llave", de: "der Schlüssel", pos: "noun", level: "A2", topic: "Zuhause", ex: "He perdido las llaves del coche.", exDe: "Ich habe die Autoschlüssel verloren." },

  // --- Essen & Trinken ---
  { es: "el agua", de: "das Wasser", pos: "noun", level: "A1", topic: "Essen", ex: "¿Me trae un vaso de agua, por favor?", exDe: "Bringen Sie mir bitte ein Glas Wasser?" },
  { es: "el pan", de: "das Brot", pos: "noun", level: "A1", topic: "Essen", ex: "Compro pan fresco cada mañana.", exDe: "Ich kaufe jeden Morgen frisches Brot." },
  { es: "la leche", de: "die Milch", pos: "noun", level: "A1", topic: "Essen", ex: "El café con leche está muy caliente.", exDe: "Der Milchkaffee ist sehr heiß." },
  { es: "la manzana", de: "der Apfel", pos: "noun", level: "A1", topic: "Essen", ex: "Como una manzana después de comer.", exDe: "Ich esse nach dem Essen einen Apfel." },
  { es: "el queso", de: "der Käse", pos: "noun", level: "A1", topic: "Essen", ex: "Este queso viene de Manchega.", exDe: "Dieser Käse kommt aus der Mancha." },
  { es: "la carne", de: "das Fleisch", pos: "noun", level: "A1", topic: "Essen", ex: "No como carne los viernes.", exDe: "Freitags esse ich kein Fleisch." },
  { es: "el pescado", de: "der Fisch", pos: "noun", level: "A1", topic: "Essen", ex: "En Galicia el pescado es excelente.", exDe: "In Galicien ist der Fisch ausgezeichnet." },
  { es: "el desayuno", de: "das Frühstück", pos: "noun", level: "A2", topic: "Essen", ex: "El desayuno se sirve hasta las diez.", exDe: "Das Frühstück wird bis zehn Uhr serviert." },
  { es: "la cuenta", de: "die Rechnung", pos: "noun", level: "A2", topic: "Essen", ex: "La cuenta, por favor.", exDe: "Die Rechnung, bitte." },
  { es: "probar", de: "probieren|kosten", pos: "verb", level: "A2", topic: "Essen", ex: "¿Quieres probar el gazpacho?", exDe: "Willst du den Gazpacho probieren?" },

  // --- Zeit ---
  { es: "el día", de: "der Tag", pos: "noun", level: "A1", topic: "Zeit", ex: "Ha sido un día muy largo.", exDe: "Es war ein sehr langer Tag." },
  { es: "la semana", de: "die Woche", pos: "noun", level: "A1", topic: "Zeit", ex: "La semana que viene tengo vacaciones.", exDe: "Nächste Woche habe ich Urlaub." },
  { es: "el año", de: "das Jahr", pos: "noun", level: "A1", topic: "Zeit", ex: "Vivo aquí desde hace un año.", exDe: "Ich wohne seit einem Jahr hier." },
  { es: "hoy", de: "heute", pos: "adv", level: "A1", topic: "Zeit", ex: "Hoy no tengo tiempo.", exDe: "Heute habe ich keine Zeit." },
  { es: "mañana", de: "morgen|der Morgen", pos: "adv", level: "A1", topic: "Zeit", ex: "Mañana empieza el curso.", exDe: "Morgen beginnt der Kurs." },
  { es: "ayer", de: "gestern", pos: "adv", level: "A1", topic: "Zeit", ex: "Ayer llovió todo el día.", exDe: "Gestern hat es den ganzen Tag geregnet." },
  { es: "siempre", de: "immer", pos: "adv", level: "A1", topic: "Zeit", ex: "Siempre llega tarde.", exDe: "Er kommt immer zu spät." },
  { es: "nunca", de: "nie|niemals", pos: "adv", level: "A1", topic: "Zeit", ex: "Nunca he estado en Perú.", exDe: "Ich war noch nie in Peru." },
  { es: "a menudo", de: "oft|häufig", pos: "adv", level: "A2", topic: "Zeit", ex: "A menudo salgo a correr por la mañana.", exDe: "Ich gehe oft morgens laufen." },
  { es: "temprano", de: "früh", pos: "adv", level: "A2", topic: "Zeit", ex: "Mañana tengo que levantarme temprano.", exDe: "Morgen muss ich früh aufstehen." },

  // --- Verben A1/A2 ---
  { es: "ser", de: "sein", pos: "verb", level: "A1", topic: "Verben", ex: "Soy de Alemania.", exDe: "Ich bin aus Deutschland." },
  { es: "estar", de: "sein|sich befinden", pos: "verb", level: "A1", topic: "Verben", ex: "Estoy en la oficina.", exDe: "Ich bin im Büro." },
  { es: "tener", de: "haben", pos: "verb", level: "A1", topic: "Verben", ex: "Tengo dos hermanas.", exDe: "Ich habe zwei Schwestern." },
  { es: "hacer", de: "machen|tun", pos: "verb", level: "A1", topic: "Verben", ex: "¿Qué haces el fin de semana?", exDe: "Was machst du am Wochenende?" },
  { es: "ir", de: "gehen|fahren", pos: "verb", level: "A1", topic: "Verben", ex: "Voy al mercado.", exDe: "Ich gehe zum Markt." },
  { es: "hablar", de: "sprechen|reden", pos: "verb", level: "A1", topic: "Verben", ex: "Hablo un poco de español.", exDe: "Ich spreche ein bisschen Spanisch." },
  { es: "comer", de: "essen", pos: "verb", level: "A1", topic: "Verben", ex: "Comemos a las dos.", exDe: "Wir essen um zwei." },
  { es: "beber", de: "trinken", pos: "verb", level: "A1", topic: "Verben", ex: "Bebo mucha agua al día.", exDe: "Ich trinke viel Wasser am Tag." },
  { es: "vivir", de: "leben|wohnen", pos: "verb", level: "A1", topic: "Verben", ex: "Vivimos en el centro.", exDe: "Wir wohnen im Zentrum." },
  { es: "trabajar", de: "arbeiten", pos: "verb", level: "A1", topic: "Verben", ex: "Trabajo desde casa.", exDe: "Ich arbeite von zu Hause." },
  { es: "aprender", de: "lernen", pos: "verb", level: "A1", topic: "Verben", ex: "Aprendo español desde enero.", exDe: "Ich lerne seit Januar Spanisch." },
  { es: "entender", de: "verstehen", pos: "verb", level: "A2", topic: "Verben", ex: "No entiendo esta palabra.", exDe: "Ich verstehe dieses Wort nicht." },
  { es: "escribir", de: "schreiben", pos: "verb", level: "A1", topic: "Verben", ex: "Te escribo un correo esta tarde.", exDe: "Ich schreibe dir heute Nachmittag eine E-Mail." },
  { es: "leer", de: "lesen", pos: "verb", level: "A1", topic: "Verben", ex: "Leo una novela española.", exDe: "Ich lese einen spanischen Roman." },
  { es: "comprar", de: "kaufen", pos: "verb", level: "A1", topic: "Verben", ex: "Quiero comprar un billete.", exDe: "Ich möchte eine Fahrkarte kaufen." },
  { es: "pagar", de: "bezahlen|zahlen", pos: "verb", level: "A2", topic: "Verben", ex: "¿Puedo pagar con tarjeta?", exDe: "Kann ich mit Karte zahlen?" },
  { es: "esperar", de: "warten|hoffen", pos: "verb", level: "A2", topic: "Verben", ex: "Espero el autobús desde hace media hora.", exDe: "Ich warte seit einer halben Stunde auf den Bus." },
  { es: "recordar", de: "sich erinnern|erinnern", pos: "verb", level: "A2", topic: "Verben", ex: "No recuerdo su nombre.", exDe: "Ich erinnere mich nicht an seinen Namen." },
  { es: "olvidar", de: "vergessen", pos: "verb", level: "A2", topic: "Verben", ex: "He olvidado el móvil en casa.", exDe: "Ich habe das Handy zu Hause vergessen." },
  { es: "intentar", de: "versuchen", pos: "verb", level: "A2", topic: "Verben", ex: "Voy a intentarlo otra vez.", exDe: "Ich werde es noch einmal versuchen." },
  { es: "conseguir", de: "erreichen|schaffen|bekommen", pos: "verb", level: "B1", topic: "Verben", ex: "Por fin conseguí una entrevista.", exDe: "Endlich habe ich ein Vorstellungsgespräch bekommen." },
  { es: "elegir", de: "wählen|auswählen", pos: "verb", level: "B1", topic: "Verben", ex: "Tienes que elegir entre dos opciones.", exDe: "Du musst zwischen zwei Optionen wählen." },
  { es: "quedarse", de: "bleiben", pos: "verb", level: "B1", topic: "Verben", ex: "Me quedo en casa esta noche.", exDe: "Ich bleibe heute Abend zu Hause." },
  { es: "acordarse de", de: "sich erinnern an", pos: "verb", level: "B1", topic: "Verben", ex: "¿Te acuerdas de aquel verano?", exDe: "Erinnerst du dich an jenen Sommer?" },
  { es: "darse cuenta de", de: "bemerken|merken", pos: "verb", level: "B1", topic: "Verben", ex: "Me di cuenta del error demasiado tarde.", exDe: "Ich habe den Fehler zu spät bemerkt." },

  // --- Stadt & Reisen ---
  { es: "la ciudad", de: "die Stadt", pos: "noun", level: "A1", topic: "Stadt", ex: "Sevilla es una ciudad preciosa.", exDe: "Sevilla ist eine wunderschöne Stadt." },
  { es: "la calle", de: "die Straße", pos: "noun", level: "A1", topic: "Stadt", ex: "Vivo en la calle Mayor.", exDe: "Ich wohne in der Calle Mayor." },
  { es: "la tienda", de: "der Laden|das Geschäft", pos: "noun", level: "A1", topic: "Stadt", ex: "La tienda abre a las nueve.", exDe: "Der Laden öffnet um neun." },
  { es: "el coche", de: "das Auto", pos: "noun", level: "A1", topic: "Reisen", ex: "Vamos en coche hasta Valencia.", exDe: "Wir fahren mit dem Auto bis Valencia." },
  { es: "el tren", de: "der Zug", pos: "noun", level: "A1", topic: "Reisen", ex: "El tren sale del andén tres.", exDe: "Der Zug fährt von Gleis drei ab." },
  { es: "el avión", de: "das Flugzeug", pos: "noun", level: "A1", topic: "Reisen", ex: "El avión aterriza a las siete.", exDe: "Das Flugzeug landet um sieben." },
  { es: "el viaje", de: "die Reise", pos: "noun", level: "A2", topic: "Reisen", ex: "El viaje dura cinco horas.", exDe: "Die Reise dauert fünf Stunden." },
  { es: "el billete", de: "die Fahrkarte|das Ticket", pos: "noun", level: "A2", topic: "Reisen", ex: "He comprado un billete de ida y vuelta.", exDe: "Ich habe eine Hin- und Rückfahrkarte gekauft." },
  { es: "el alojamiento", de: "die Unterkunft", pos: "noun", level: "B1", topic: "Reisen", ex: "El alojamiento incluye el desayuno.", exDe: "Die Unterkunft schließt das Frühstück ein." },
  { es: "el retraso", de: "die Verspätung", pos: "noun", level: "B1", topic: "Reisen", ex: "El vuelo lleva dos horas de retraso.", exDe: "Der Flug hat zwei Stunden Verspätung." },

  // --- Arbeit & Studium ---
  { es: "el trabajo", de: "die Arbeit", pos: "noun", level: "A1", topic: "Arbeit", ex: "Tengo mucho trabajo esta semana.", exDe: "Ich habe diese Woche viel Arbeit." },
  { es: "la empresa", de: "das Unternehmen|die Firma", pos: "noun", level: "A2", topic: "Arbeit", ex: "La empresa tiene cien empleados.", exDe: "Das Unternehmen hat hundert Angestellte." },
  { es: "la reunión", de: "die Besprechung|das Treffen", pos: "noun", level: "A2", topic: "Arbeit", ex: "La reunión empieza a las diez.", exDe: "Die Besprechung beginnt um zehn." },
  { es: "el sueldo", de: "das Gehalt", pos: "noun", level: "B1", topic: "Arbeit", ex: "El sueldo se paga a fin de mes.", exDe: "Das Gehalt wird am Monatsende gezahlt." },
  { es: "el jefe", de: "der Chef", pos: "noun", level: "A2", topic: "Arbeit", ex: "Mi jefe está de viaje.", exDe: "Mein Chef ist auf Reisen." },
  { es: "la formación", de: "die Ausbildung", pos: "noun", level: "B1", topic: "Arbeit", ex: "Necesita una formación específica.", exDe: "Er braucht eine spezielle Ausbildung." },
  { es: "el plazo", de: "die Frist", pos: "noun", level: "B1", topic: "Arbeit", ex: "El plazo termina el viernes.", exDe: "Die Frist endet am Freitag." },
  { es: "la ventaja", de: "der Vorteil", pos: "noun", level: "B1", topic: "Arbeit", ex: "La mayor ventaja es la flexibilidad.", exDe: "Der größte Vorteil ist die Flexibilität." },
  { es: "el riesgo", de: "das Risiko", pos: "noun", level: "B1", topic: "Arbeit", ex: "No quiero correr ese riesgo.", exDe: "Ich will dieses Risiko nicht eingehen." },

  // --- Adjektive ---
  { es: "grande", de: "groß", pos: "adj", level: "A1", topic: "Adjektive", ex: "Su piso es muy grande.", exDe: "Seine Wohnung ist sehr groß." },
  { es: "pequeño", de: "klein", pos: "adj", level: "A1", topic: "Adjektive", ex: "Es un pueblo pequeño y tranquilo.", exDe: "Es ist ein kleines, ruhiges Dorf." },
  { es: "nuevo", de: "neu", pos: "adj", level: "A1", topic: "Adjektive", ex: "Tengo un trabajo nuevo.", exDe: "Ich habe eine neue Arbeit." },
  { es: "viejo", de: "alt", pos: "adj", level: "A1", topic: "Adjektive", ex: "Este coche ya está muy viejo.", exDe: "Dieses Auto ist schon sehr alt." },
  { es: "bonito", de: "schön|hübsch", pos: "adj", level: "A1", topic: "Adjektive", ex: "¡Qué vestido tan bonito!", exDe: "Was für ein schönes Kleid!" },
  { es: "caro", de: "teuer", pos: "adj", level: "A1", topic: "Adjektive", ex: "El hotel es demasiado caro.", exDe: "Das Hotel ist zu teuer." },
  { es: "barato", de: "billig|günstig", pos: "adj", level: "A1", topic: "Adjektive", ex: "Encontré un vuelo muy barato.", exDe: "Ich habe einen sehr günstigen Flug gefunden." },
  { es: "difícil", de: "schwierig|schwer", pos: "adj", level: "A1", topic: "Adjektive", ex: "El examen fue bastante difícil.", exDe: "Die Prüfung war ziemlich schwierig." },
  { es: "fácil", de: "einfach|leicht", pos: "adj", level: "A1", topic: "Adjektive", ex: "Esta receta es muy fácil.", exDe: "Dieses Rezept ist sehr einfach." },
  { es: "cansado", de: "müde", pos: "adj", level: "A2", topic: "Adjektive", ex: "Estoy cansado después del viaje.", exDe: "Ich bin nach der Reise müde." },
  { es: "contento", de: "zufrieden|froh", pos: "adj", level: "A2", topic: "Adjektive", ex: "Estoy muy contento con el resultado.", exDe: "Ich bin sehr zufrieden mit dem Ergebnis." },
  { es: "ocupado", de: "beschäftigt|besetzt", pos: "adj", level: "A2", topic: "Adjektive", ex: "Hoy estoy muy ocupada.", exDe: "Heute bin ich sehr beschäftigt." },
  { es: "amable", de: "freundlich|nett", pos: "adj", level: "A2", topic: "Adjektive", ex: "La camarera fue muy amable.", exDe: "Die Kellnerin war sehr freundlich." },
  { es: "raro", de: "seltsam|selten", pos: "adj", level: "B1", topic: "Adjektive", ex: "Me parece un poco raro.", exDe: "Das kommt mir etwas seltsam vor." },
  { es: "imprescindible", de: "unverzichtbar", pos: "adj", level: "B1", topic: "Adjektive", ex: "Es imprescindible reservar antes.", exDe: "Es ist unverzichtbar, vorher zu reservieren." },
  { es: "disponible", de: "verfügbar", pos: "adj", level: "B1", topic: "Adjektive", ex: "No hay habitaciones disponibles.", exDe: "Es sind keine Zimmer verfügbar." },

  // --- Redemittel / Konnektoren ---
  { es: "por supuesto", de: "selbstverständlich|natürlich", pos: "phrase", level: "A2", topic: "Redemittel", ex: "—¿Me ayudas? —¡Por supuesto!", exDe: "„Hilfst du mir?“ – „Selbstverständlich!“" },
  { es: "sin embargo", de: "jedoch|allerdings", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Es caro; sin embargo, vale la pena.", exDe: "Es ist teuer; allerdings lohnt es sich." },
  { es: "por eso", de: "deshalb|deswegen", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Llovía, por eso no salimos.", exDe: "Es regnete, deshalb sind wir nicht rausgegangen." },
  { es: "en cambio", de: "hingegen|dagegen", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Yo prefiero el mar; ella, en cambio, la montaña.", exDe: "Ich mag das Meer lieber; sie hingegen die Berge." },
  { es: "a lo mejor", de: "vielleicht", pos: "phrase", level: "B1", topic: "Redemittel", ex: "A lo mejor vienen más tarde.", exDe: "Vielleicht kommen sie später." },
  { es: "de repente", de: "plötzlich", pos: "phrase", level: "B1", topic: "Redemittel", ex: "De repente se apagó la luz.", exDe: "Plötzlich ging das Licht aus." },
  { es: "vale la pena", de: "es lohnt sich", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Vale la pena visitar el museo.", exDe: "Es lohnt sich, das Museum zu besuchen." },
  { es: "tener ganas de", de: "Lust haben auf", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Tengo ganas de ver el mar.", exDe: "Ich habe Lust, das Meer zu sehen." },
  { es: "echar de menos", de: "vermissen", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Echo de menos a mi familia.", exDe: "Ich vermisse meine Familie." },
  { es: "dar igual", de: "egal sein", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Me da igual dónde comemos.", exDe: "Mir ist egal, wo wir essen." }
];
