/* Startdeck Spanisch -> Deutsch.
   Jeder Eintrag: es, de (Alternativen mit |), pos, level, topic, ex (Beispielsatz), exDe */
const DECK = [
  // --- A1: Grundlagen / Personen ---
  { es: "el hombre", de: "der Mann", pos: "noun", level: "A1", topic: "Menschen", ex: "El hombre lee el periódico.", exDe: "Der Mann liest die Zeitung." },
  { es: "la mujer", de: "die Frau", pos: "noun", level: "A1", topic: "Menschen", ex: "La mujer trabaja en un hospital.", exDe: "Die Frau arbeitet in einem Krankenhaus." },
  { es: "el niño", de: "das Kind|der Junge", pos: "noun", level: "A1", topic: "Menschen", ex: "El niño juega en el parque.", exDe: "Das Kind spielt im Park." },
  { es: "el amigo", de: "der Freund", pos: "noun", level: "A1", topic: "Menschen", ex: "Mi amigo vive en Madrid.", exDe: "Mein Freund wohnt in Madrid." },
  { es: "la familia", de: "die Familie", pos: "noun", level: "A1", topic: "Menschen", ex: "Toda la familia come junta los domingos.", exDe: "Die ganze Familie isst sonntags zusammen." },
  { es: "el hermano", de: "der Bruder", pos: "noun", level: "A1", topic: "Menschen", ex: "Mi hermano tiene veinte años.", exDe: "Mein Bruder ist zwanzig Jahre alt." },
  { es: "la hija", de: "die Tochter", pos: "noun", level: "A1", topic: "Menschen", ex: "Su hija estudia medicina.", exDe: "Ihre Tochter studiert Medizin." },
  { es: "el vecino", de: "der Nachbar", pos: "noun", level: "A2", topic: "Menschen", ex: "El vecino siempre saluda por la mañana.", exDe: "Der Nachbar grüßt morgens immer." },

  // --- Alltag / Zuhause ---
  { es: "la casa", de: "das Haus", pos: "noun", level: "A1", topic: "Zuhause", ex: "Nuestra casa está cerca de la playa.", exDe: "Unser Haus ist in der Nähe des Strandes." },
  { es: "la puerta", de: "die Tür", pos: "noun", level: "A1", topic: "Zuhause", ex: "Por favor, cierra la puerta.", exDe: "Bitte schließ die Tür." },
  { es: "la ventana", de: "das Fenster", pos: "noun", level: "A1", topic: "Zuhause", ex: "Abro la ventana porque hace calor.", exDe: "Ich öffne das Fenster, weil es heiß ist." },
  { es: "la mesa", de: "der Tisch", pos: "noun", level: "A1", topic: "Zuhause", ex: "La comida ya está en la mesa.", exDe: "Das Essen steht schon auf dem Tisch." },
  { es: "la silla", de: "der Stuhl", pos: "noun", level: "A1", topic: "Zuhause", ex: "Esta silla es muy cómoda.", exDe: "Dieser Stuhl ist sehr bequem." },
  { es: "la cama", de: "das Bett", pos: "noun", level: "A1", topic: "Zuhause", ex: "Los sábados me quedo en la cama.", exDe: "Samstags bleibe ich im Bett." },
  { es: "la cocina", de: "die Küche", pos: "noun", level: "A1", topic: "Zuhause", ex: "Mi madre está en la cocina.", exDe: "Meine Mutter ist in der Küche." },
  { es: "la llave", de: "der Schlüssel", pos: "noun", level: "A2", topic: "Zuhause", ex: "He perdido las llaves del coche.", exDe: "Ich habe die Autoschlüssel verloren." },

  // --- Essen & Trinken ---
  { es: "el agua", de: "das Wasser", pos: "noun", level: "A1", topic: "Essen", ex: "¿Me trae un vaso de agua, por favor?", exDe: "Bringen Sie mir bitte ein Glas Wasser?" },
  { es: "el pan", de: "das Brot", pos: "noun", level: "A1", topic: "Essen", ex: "Compro pan fresco cada mañana.", exDe: "Ich kaufe jeden Morgen frisches Brot." },
  { es: "la leche", de: "die Milch", pos: "noun", level: "A1", topic: "Essen", ex: "El café con leche está muy caliente.", exDe: "Der Milchkaffee ist sehr heiß." },
  { es: "la manzana", de: "der Apfel", pos: "noun", level: "A1", topic: "Essen", ex: "Como una manzana después de comer.", exDe: "Ich esse nach dem Essen einen Apfel." },
  { es: "el queso", de: "der Käse", pos: "noun", level: "A1", topic: "Essen", ex: "Este queso viene de Manchega.", exDe: "Dieser Käse kommt aus der Mancha." },
  { es: "la carne", de: "das Fleisch", pos: "noun", level: "A1", topic: "Essen", ex: "No como carne los viernes.", exDe: "Freitags esse ich kein Fleisch." },
  { es: "el pescado", de: "der Fisch", pos: "noun", level: "A1", topic: "Essen", ex: "En Galicia el pescado es excelente.", exDe: "In Galicien ist der Fisch ausgezeichnet." },
  { es: "el desayuno", de: "das Frühstück", pos: "noun", level: "A2", topic: "Essen", ex: "El desayuno se sirve hasta las diez.", exDe: "Das Frühstück wird bis zehn Uhr serviert." },
  { es: "la cuenta", de: "die Rechnung", pos: "noun", level: "A2", topic: "Essen", ex: "La cuenta, por favor.", exDe: "Die Rechnung, bitte." },
  { es: "probar", de: "probieren|kosten", pos: "verb", level: "A2", topic: "Essen", ex: "¿Quieres probar el gazpacho?", exDe: "Willst du den Gazpacho probieren?" },

  // --- Zeit ---
  { es: "el día", de: "der Tag", pos: "noun", level: "A1", topic: "Zeit", ex: "Ha sido un día muy largo.", exDe: "Es war ein sehr langer Tag." },
  { es: "la semana", de: "die Woche", pos: "noun", level: "A1", topic: "Zeit", ex: "La semana que viene tengo vacaciones.", exDe: "Nächste Woche habe ich Urlaub." },
  { es: "el año", de: "das Jahr", pos: "noun", level: "A1", topic: "Zeit", ex: "Vivo aquí desde hace un año.", exDe: "Ich wohne seit einem Jahr hier." },
  { es: "hoy", de: "heute", pos: "adv", level: "A1", topic: "Zeit", ex: "Hoy no tengo tiempo.", exDe: "Heute habe ich keine Zeit." },
  { es: "mañana", de: "morgen|der Morgen", pos: "adv", level: "A1", topic: "Zeit", ex: "Mañana empieza el curso.", exDe: "Morgen beginnt der Kurs." },
  { es: "ayer", de: "gestern", pos: "adv", level: "A1", topic: "Zeit", ex: "Ayer llovió todo el día.", exDe: "Gestern hat es den ganzen Tag geregnet." },
  { es: "siempre", de: "immer", pos: "adv", level: "A1", topic: "Zeit", ex: "Siempre llega tarde.", exDe: "Er kommt immer zu spät." },
  { es: "nunca", de: "nie|niemals", pos: "adv", level: "A1", topic: "Zeit", ex: "Nunca he estado en Perú.", exDe: "Ich war noch nie in Peru." },
  { es: "a menudo", de: "oft|häufig", pos: "adv", level: "A2", topic: "Zeit", ex: "A menudo salgo a correr por la mañana.", exDe: "Ich gehe oft morgens laufen." },
  { es: "temprano", de: "früh", pos: "adv", level: "A2", topic: "Zeit", ex: "Mañana tengo que levantarme temprano.", exDe: "Morgen muss ich früh aufstehen." },

  // --- Verben A1/A2 ---
  { es: "ser", de: "sein", pos: "verb", level: "A1", topic: "Verben", ex: "Soy de Alemania.", exDe: "Ich bin aus Deutschland." },
  { es: "estar", de: "sein|sich befinden", pos: "verb", level: "A1", topic: "Verben", ex: "Estoy en la oficina.", exDe: "Ich bin im Büro." },
  { es: "tener", de: "haben", pos: "verb", level: "A1", topic: "Verben", ex: "Tengo dos hermanas.", exDe: "Ich habe zwei Schwestern." },
  { es: "hacer", de: "machen|tun", pos: "verb", level: "A1", topic: "Verben", ex: "¿Qué haces el fin de semana?", exDe: "Was machst du am Wochenende?" },
  { es: "ir", de: "gehen|fahren", pos: "verb", level: "A1", topic: "Verben", ex: "Voy al mercado.", exDe: "Ich gehe zum Markt." },
  { es: "hablar", de: "sprechen|reden", pos: "verb", level: "A1", topic: "Verben", ex: "Hablo un poco de español.", exDe: "Ich spreche ein bisschen Spanisch." },
  { es: "comer", de: "essen", pos: "verb", level: "A1", topic: "Verben", ex: "Comemos a las dos.", exDe: "Wir essen um zwei." },
  { es: "beber", de: "trinken", pos: "verb", level: "A1", topic: "Verben", ex: "Bebo mucha agua al día.", exDe: "Ich trinke viel Wasser am Tag." },
  { es: "vivir", de: "leben|wohnen", pos: "verb", level: "A1", topic: "Verben", ex: "Vivimos en el centro.", exDe: "Wir wohnen im Zentrum." },
  { es: "trabajar", de: "arbeiten", pos: "verb", level: "A1", topic: "Verben", ex: "Trabajo desde casa.", exDe: "Ich arbeite von zu Hause." },
  { es: "aprender", de: "lernen", pos: "verb", level: "A1", topic: "Verben", ex: "Aprendo español desde enero.", exDe: "Ich lerne seit Januar Spanisch." },
  { es: "entender", de: "verstehen", pos: "verb", level: "A2", topic: "Verben", ex: "No entiendo esta palabra.", exDe: "Ich verstehe dieses Wort nicht." },
  { es: "escribir", de: "schreiben", pos: "verb", level: "A1", topic: "Verben", ex: "Te escribo un correo esta tarde.", exDe: "Ich schreibe dir heute Nachmittag eine E-Mail." },
  { es: "leer", de: "lesen", pos: "verb", level: "A1", topic: "Verben", ex: "Leo una novela española.", exDe: "Ich lese einen spanischen Roman." },
  { es: "comprar", de: "kaufen", pos: "verb", level: "A1", topic: "Verben", ex: "Quiero comprar un billete.", exDe: "Ich möchte eine Fahrkarte kaufen." },
  { es: "pagar", de: "bezahlen|zahlen", pos: "verb", level: "A2", topic: "Verben", ex: "¿Puedo pagar con tarjeta?", exDe: "Kann ich mit Karte zahlen?" },
  { es: "esperar", de: "warten|hoffen", pos: "verb", level: "A2", topic: "Verben", ex: "Espero el autobús desde hace media hora.", exDe: "Ich warte seit einer halben Stunde auf den Bus." },
  { es: "recordar", de: "sich erinnern|erinnern", pos: "verb", level: "A2", topic: "Verben", ex: "No recuerdo su nombre.", exDe: "Ich erinnere mich nicht an seinen Namen." },
  { es: "olvidar", de: "vergessen", pos: "verb", level: "A2", topic: "Verben", ex: "He olvidado el móvil en casa.", exDe: "Ich habe das Handy zu Hause vergessen." },
  { es: "intentar", de: "versuchen", pos: "verb", level: "A2", topic: "Verben", ex: "Voy a intentarlo otra vez.", exDe: "Ich werde es noch einmal versuchen." },
  { es: "conseguir", de: "erreichen|schaffen|bekommen", pos: "verb", level: "B1", topic: "Verben", ex: "Por fin conseguí una entrevista.", exDe: "Endlich habe ich ein Vorstellungsgespräch bekommen." },
  { es: "elegir", de: "wählen|auswählen", pos: "verb", level: "B1", topic: "Verben", ex: "Tienes que elegir entre dos opciones.", exDe: "Du musst zwischen zwei Optionen wählen." },
  { es: "quedarse", de: "bleiben", pos: "verb", level: "B1", topic: "Verben", ex: "Me quedo en casa esta noche.", exDe: "Ich bleibe heute Abend zu Hause." },
  { es: "acordarse de", de: "sich erinnern an", pos: "verb", level: "B1", topic: "Verben", ex: "¿Te acuerdas de aquel verano?", exDe: "Erinnerst du dich an jenen Sommer?" },
  { es: "darse cuenta de", de: "bemerken|merken", pos: "verb", level: "B1", topic: "Verben", ex: "Me di cuenta del error demasiado tarde.", exDe: "Ich habe den Fehler zu spät bemerkt." },

  // --- Stadt & Reisen ---
  { es: "la ciudad", de: "die Stadt", pos: "noun", level: "A1", topic: "Stadt", ex: "Sevilla es una ciudad preciosa.", exDe: "Sevilla ist eine wunderschöne Stadt." },
  { es: "la calle", de: "die Straße", pos: "noun", level: "A1", topic: "Stadt", ex: "Vivo en la calle Mayor.", exDe: "Ich wohne in der Calle Mayor." },
  { es: "la tienda", de: "der Laden|das Geschäft", pos: "noun", level: "A1", topic: "Stadt", ex: "La tienda abre a las nueve.", exDe: "Der Laden öffnet um neun." },
  { es: "el coche", de: "das Auto", pos: "noun", level: "A1", topic: "Reisen", ex: "Vamos en coche hasta Valencia.", exDe: "Wir fahren mit dem Auto bis Valencia." },
  { es: "el tren", de: "der Zug", pos: "noun", level: "A1", topic: "Reisen", ex: "El tren sale del andén tres.", exDe: "Der Zug fährt von Gleis drei ab." },
  { es: "el avión", de: "das Flugzeug", pos: "noun", level: "A1", topic: "Reisen", ex: "El avión aterriza a las siete.", exDe: "Das Flugzeug landet um sieben." },
  { es: "el viaje", de: "die Reise", pos: "noun", level: "A2", topic: "Reisen", ex: "El viaje dura cinco horas.", exDe: "Die Reise dauert fünf Stunden." },
  { es: "el billete", de: "die Fahrkarte|das Ticket", pos: "noun", level: "A2", topic: "Reisen", ex: "He comprado un billete de ida y vuelta.", exDe: "Ich habe eine Hin- und Rückfahrkarte gekauft." },
  { es: "el alojamiento", de: "die Unterkunft", pos: "noun", level: "B1", topic: "Reisen", ex: "El alojamiento incluye el desayuno.", exDe: "Die Unterkunft schließt das Frühstück ein." },
  { es: "el retraso", de: "die Verspätung", pos: "noun", level: "B1", topic: "Reisen", ex: "El vuelo lleva dos horas de retraso.", exDe: "Der Flug hat zwei Stunden Verspätung." },

  // --- Arbeit & Studium ---
  { es: "el trabajo", de: "die Arbeit", pos: "noun", level: "A1", topic: "Arbeit", ex: "Tengo mucho trabajo esta semana.", exDe: "Ich habe diese Woche viel Arbeit." },
  { es: "la empresa", de: "das Unternehmen|die Firma", pos: "noun", level: "A2", topic: "Arbeit", ex: "La empresa tiene cien empleados.", exDe: "Das Unternehmen hat hundert Angestellte." },
  { es: "la reunión", de: "die Besprechung|das Treffen", pos: "noun", level: "A2", topic: "Arbeit", ex: "La reunión empieza a las diez.", exDe: "Die Besprechung beginnt um zehn." },
  { es: "el sueldo", de: "das Gehalt", pos: "noun", level: "B1", topic: "Arbeit", ex: "El sueldo se paga a fin de mes.", exDe: "Das Gehalt wird am Monatsende gezahlt." },
  { es: "el jefe", de: "der Chef", pos: "noun", level: "A2", topic: "Arbeit", ex: "Mi jefe está de viaje.", exDe: "Mein Chef ist auf Reisen." },
  { es: "la formación", de: "die Ausbildung", pos: "noun", level: "B1", topic: "Arbeit", ex: "Necesita una formación específica.", exDe: "Er braucht eine spezielle Ausbildung." },
  { es: "el plazo", de: "die Frist", pos: "noun", level: "B1", topic: "Arbeit", ex: "El plazo termina el viernes.", exDe: "Die Frist endet am Freitag." },
  { es: "la ventaja", de: "der Vorteil", pos: "noun", level: "B1", topic: "Arbeit", ex: "La mayor ventaja es la flexibilidad.", exDe: "Der größte Vorteil ist die Flexibilität." },
  { es: "el riesgo", de: "das Risiko", pos: "noun", level: "B1", topic: "Arbeit", ex: "No quiero correr ese riesgo.", exDe: "Ich will dieses Risiko nicht eingehen." },

  // --- Adjektive ---
  { es: "grande", de: "groß", pos: "adj", level: "A1", topic: "Adjektive", ex: "Su piso es muy grande.", exDe: "Seine Wohnung ist sehr groß." },
  { es: "pequeño", de: "klein", pos: "adj", level: "A1", topic: "Adjektive", ex: "Es un pueblo pequeño y tranquilo.", exDe: "Es ist ein kleines, ruhiges Dorf." },
  { es: "nuevo", de: "neu", pos: "adj", level: "A1", topic: "Adjektive", ex: "Tengo un trabajo nuevo.", exDe: "Ich habe eine neue Arbeit." },
  { es: "viejo", de: "alt", pos: "adj", level: "A1", topic: "Adjektive", ex: "Este coche ya está muy viejo.", exDe: "Dieses Auto ist schon sehr alt." },
  { es: "bonito", de: "schön|hübsch", pos: "adj", level: "A1", topic: "Adjektive", ex: "¡Qué vestido tan bonito!", exDe: "Was für ein schönes Kleid!" },
  { es: "caro", de: "teuer", pos: "adj", level: "A1", topic: "Adjektive", ex: "El hotel es demasiado caro.", exDe: "Das Hotel ist zu teuer." },
  { es: "barato", de: "billig|günstig", pos: "adj", level: "A1", topic: "Adjektive", ex: "Encontré un vuelo muy barato.", exDe: "Ich habe einen sehr günstigen Flug gefunden." },
  { es: "difícil", de: "schwierig|schwer", pos: "adj", level: "A1", topic: "Adjektive", ex: "El examen fue bastante difícil.", exDe: "Die Prüfung war ziemlich schwierig." },
  { es: "fácil", de: "einfach|leicht", pos: "adj", level: "A1", topic: "Adjektive", ex: "Esta receta es muy fácil.", exDe: "Dieses Rezept ist sehr einfach." },
  { es: "cansado", de: "müde", pos: "adj", level: "A2", topic: "Adjektive", ex: "Estoy cansado después del viaje.", exDe: "Ich bin nach der Reise müde." },
  { es: "contento", de: "zufrieden|froh", pos: "adj", level: "A2", topic: "Adjektive", ex: "Estoy muy contento con el resultado.", exDe: "Ich bin sehr zufrieden mit dem Ergebnis." },
  { es: "ocupado", de: "beschäftigt|besetzt", pos: "adj", level: "A2", topic: "Adjektive", ex: "Hoy estoy muy ocupada.", exDe: "Heute bin ich sehr beschäftigt." },
  { es: "amable", de: "freundlich|nett", pos: "adj", level: "A2", topic: "Adjektive", ex: "La camarera fue muy amable.", exDe: "Die Kellnerin war sehr freundlich." },
  { es: "raro", de: "seltsam|selten", pos: "adj", level: "B1", topic: "Adjektive", ex: "Me parece un poco raro.", exDe: "Das kommt mir etwas seltsam vor." },
  { es: "imprescindible", de: "unverzichtbar", pos: "adj", level: "B1", topic: "Adjektive", ex: "Es imprescindible reservar antes.", exDe: "Es ist unverzichtbar, vorher zu reservieren." },
  { es: "disponible", de: "verfügbar", pos: "adj", level: "B1", topic: "Adjektive", ex: "No hay habitaciones disponibles.", exDe: "Es sind keine Zimmer verfügbar." },

  // --- Redemittel / Konnektoren ---
  { es: "por supuesto", de: "selbstverständlich|natürlich", pos: "phrase", level: "A2", topic: "Redemittel", ex: "—¿Me ayudas? —¡Por supuesto!", exDe: "„Hilfst du mir?“ – „Selbstverständlich!“" },
  { es: "sin embargo", de: "jedoch|allerdings", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Es caro; sin embargo, vale la pena.", exDe: "Es ist teuer; allerdings lohnt es sich." },
  { es: "por eso", de: "deshalb|deswegen", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Llovía, por eso no salimos.", exDe: "Es regnete, deshalb sind wir nicht rausgegangen." },
  { es: "en cambio", de: "hingegen|dagegen", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Yo prefiero el mar; ella, en cambio, la montaña.", exDe: "Ich mag das Meer lieber; sie hingegen die Berge." },
  { es: "a lo mejor", de: "vielleicht", pos: "phrase", level: "B1", topic: "Redemittel", ex: "A lo mejor vienen más tarde.", exDe: "Vielleicht kommen sie später." },
  { es: "de repente", de: "plötzlich", pos: "phrase", level: "B1", topic: "Redemittel", ex: "De repente se apagó la luz.", exDe: "Plötzlich ging das Licht aus." },
  { es: "vale la pena", de: "es lohnt sich", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Vale la pena visitar el museo.", exDe: "Es lohnt sich, das Museum zu besuchen." },
  { es: "tener ganas de", de: "Lust haben auf", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Tengo ganas de ver el mar.", exDe: "Ich habe Lust, das Meer zu sehen." },
  { es: "echar de menos", de: "vermissen", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Echo de menos a mi familia.", exDe: "Ich vermisse meine Familie." },
  { es: "dar igual", de: "egal sein", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Me da igual dónde comemos.", exDe: "Mir ist egal, wo wir essen." },

  // --- Zahlen ---
  { es: "cero", de: "null", pos: "num", level: "A1", topic: "Zahlen", ex: "Empezamos desde cero.", exDe: "Wir fangen bei null an." },
  { es: "uno", de: "eins", pos: "num", level: "A1", topic: "Zahlen", ex: "Solo tengo uno.", exDe: "Ich habe nur eins." },
  { es: "dos", de: "zwei", pos: "num", level: "A1", topic: "Zahlen", ex: "Tengo dos gatos.", exDe: "Ich habe zwei Katzen." },
  { es: "tres", de: "drei", pos: "num", level: "A1", topic: "Zahlen", ex: "Nos vemos a las tres.", exDe: "Wir sehen uns um drei." },
  { es: "cuatro", de: "vier", pos: "num", level: "A1", topic: "Zahlen", ex: "Hay cuatro sillas.", exDe: "Es gibt vier Stühle." },
  { es: "cinco", de: "fünf", pos: "num", level: "A1", topic: "Zahlen", ex: "Faltan cinco minutos.", exDe: "Es fehlen noch fünf Minuten." },
  { es: "seis", de: "sechs", pos: "num", level: "A1", topic: "Zahlen", ex: "Son las seis en punto.", exDe: "Es ist genau sechs Uhr." },
  { es: "siete", de: "sieben", pos: "num", level: "A1", topic: "Zahlen", ex: "La tienda abre a las siete.", exDe: "Der Laden öffnet um sieben." },
  { es: "ocho", de: "acht", pos: "num", level: "A1", topic: "Zahlen", ex: "Trabajo ocho horas al día.", exDe: "Ich arbeite acht Stunden am Tag." },
  { es: "nueve", de: "neun", pos: "num", level: "A1", topic: "Zahlen", ex: "El tren llega a las nueve.", exDe: "Der Zug kommt um neun." },
  { es: "diez", de: "zehn", pos: "num", level: "A1", topic: "Zahlen", ex: "Cuento hasta diez.", exDe: "Ich zähle bis zehn." },
  { es: "once", de: "elf", pos: "num", level: "A1", topic: "Zahlen", ex: "La reunión es a las once.", exDe: "Die Besprechung ist um elf." },
  { es: "doce", de: "zwölf", pos: "num", level: "A1", topic: "Zahlen", ex: "Hay doce meses en un año.", exDe: "Ein Jahr hat zwölf Monate." },
  { es: "trece", de: "dreizehn", pos: "num", level: "A2", topic: "Zahlen", ex: "Tiene trece años.", exDe: "Er ist dreizehn Jahre alt." },
  { es: "catorce", de: "vierzehn", pos: "num", level: "A2", topic: "Zahlen", ex: "Vuelvo en catorce días.", exDe: "Ich komme in vierzehn Tagen zurück." },
  { es: "quince", de: "fünfzehn", pos: "num", level: "A2", topic: "Zahlen", ex: "Espera quince minutos.", exDe: "Warte fünfzehn Minuten." },
  { es: "dieciséis", de: "sechzehn", pos: "num", level: "A2", topic: "Zahlen", ex: "Cumple dieciséis años mañana.", exDe: "Er wird morgen sechzehn." },
  { es: "diecisiete", de: "siebzehn", pos: "num", level: "A2", topic: "Zahlen", ex: "Hay diecisiete alumnos en clase.", exDe: "Es gibt siebzehn Schüler in der Klasse." },
  { es: "dieciocho", de: "achtzehn", pos: "num", level: "A2", topic: "Zahlen", ex: "A los dieciocho puedes votar.", exDe: "Mit achtzehn darf man wählen." },
  { es: "diecinueve", de: "neunzehn", pos: "num", level: "A2", topic: "Zahlen", ex: "Nació en el siglo diecinueve.", exDe: "Er wurde im neunzehnten Jahrhundert geboren." },
  { es: "veinte", de: "zwanzig", pos: "num", level: "A1", topic: "Zahlen", ex: "Cuesta veinte euros.", exDe: "Es kostet zwanzig Euro." },
  { es: "treinta", de: "dreißig", pos: "num", level: "A2", topic: "Zahlen", ex: "El curso dura treinta días.", exDe: "Der Kurs dauert dreißig Tage." },
  { es: "cuarenta", de: "vierzig", pos: "num", level: "A2", topic: "Zahlen", ex: "Trabaja cuarenta horas por semana.", exDe: "Er arbeitet vierzig Stunden pro Woche." },
  { es: "cincuenta", de: "fünfzig", pos: "num", level: "A2", topic: "Zahlen", ex: "Hay cincuenta personas aquí.", exDe: "Hier sind fünfzig Personen." },
  { es: "sesenta", de: "sechzig", pos: "num", level: "A2", topic: "Zahlen", ex: "Una hora tiene sesenta minutos.", exDe: "Eine Stunde hat sechzig Minuten." },
  { es: "setenta", de: "siebzig", pos: "num", level: "A2", topic: "Zahlen", ex: "Mi abuelo tiene setenta años.", exDe: "Mein Großvater ist siebzig Jahre alt." },
  { es: "ochenta", de: "achtzig", pos: "num", level: "A2", topic: "Zahlen", ex: "El descuento es del ochenta por ciento.", exDe: "Der Rabatt beträgt achtzig Prozent." },
  { es: "noventa", de: "neunzig", pos: "num", level: "A2", topic: "Zahlen", ex: "Casi noventa personas vinieron.", exDe: "Fast neunzig Personen sind gekommen." },
  { es: "cien", de: "hundert", pos: "num", level: "A1", topic: "Zahlen", ex: "El billete vale cien euros.", exDe: "Der Schein ist hundert Euro wert." },
  { es: "mil", de: "tausend", pos: "num", level: "A2", topic: "Zahlen", ex: "Cuesta mil euros.", exDe: "Es kostet tausend Euro." },
  { es: "el millón", de: "die Million", pos: "noun", level: "B1", topic: "Zahlen", ex: "Ganó un millón en la lotería.", exDe: "Er gewann eine Million im Lotto." },
  { es: "primero", de: "erste|erster", pos: "adj", level: "A2", topic: "Zahlen", ex: "Es mi primer día de trabajo.", exDe: "Es ist mein erster Arbeitstag." },
  { es: "segundo", de: "zweite|zweiter", pos: "adj", level: "A2", topic: "Zahlen", ex: "Vivo en el segundo piso.", exDe: "Ich wohne im zweiten Stock." },
  { es: "tercero", de: "dritte|dritter", pos: "adj", level: "A2", topic: "Zahlen", ex: "Llegó en tercer lugar.", exDe: "Er kam als Dritter an." },
  { es: "cuarto", de: "vierte|vierter", pos: "adj", level: "B1", topic: "Zahlen", ex: "Es la cuarta vez que lo intento.", exDe: "Es ist das vierte Mal, dass ich es versuche." },
  { es: "quinto", de: "fünfte|fünfter", pos: "adj", level: "B1", topic: "Zahlen", ex: "Está en el quinto lugar.", exDe: "Er liegt auf dem fünften Platz." },
  { es: "décimo", de: "zehnte|zehnter", pos: "adj", level: "B1", topic: "Zahlen", ex: "Celebramos el décimo aniversario.", exDe: "Wir feiern das zehnte Jubiläum." },

  // --- Farben ---
  { es: "rojo", de: "rot", pos: "adj", level: "A1", topic: "Farben", ex: "El coche rojo es nuevo.", exDe: "Das rote Auto ist neu." },
  { es: "azul", de: "blau", pos: "adj", level: "A1", topic: "Farben", ex: "El cielo está muy azul hoy.", exDe: "Der Himmel ist heute sehr blau." },
  { es: "verde", de: "grün", pos: "adj", level: "A1", topic: "Farben", ex: "Me gusta el té verde.", exDe: "Ich mag grünen Tee." },
  { es: "amarillo", de: "gelb", pos: "adj", level: "A1", topic: "Farben", ex: "Lleva una camisa amarilla.", exDe: "Er trägt ein gelbes Hemd." },
  { es: "negro", de: "schwarz", pos: "adj", level: "A1", topic: "Farben", ex: "El gato negro duerme en el sofá.", exDe: "Die schwarze Katze schläft auf dem Sofa." },
  { es: "blanco", de: "weiß", pos: "adj", level: "A1", topic: "Farben", ex: "La pared es blanca.", exDe: "Die Wand ist weiß." },
  { es: "gris", de: "grau", pos: "adj", level: "A2", topic: "Farben", ex: "El cielo está gris hoy.", exDe: "Der Himmel ist heute grau." },
  { es: "marrón", de: "braun", pos: "adj", level: "A2", topic: "Farben", ex: "Compré unos zapatos marrones.", exDe: "Ich habe braune Schuhe gekauft." },
  { es: "rosa", de: "rosa|rosarot", pos: "adj", level: "A2", topic: "Farben", ex: "Su habitación es rosa.", exDe: "Ihr Zimmer ist rosa." },
  { es: "naranja", de: "orange", pos: "adj", level: "A2", topic: "Farben", ex: "El atardecer es naranja.", exDe: "Der Sonnenuntergang ist orange." },
  { es: "morado", de: "violett|lila", pos: "adj", level: "B1", topic: "Farben", ex: "Las flores son moradas.", exDe: "Die Blumen sind violett." },
  { es: "dorado", de: "golden", pos: "adj", level: "B1", topic: "Farben", ex: "Tiene un anillo dorado.", exDe: "Sie hat einen goldenen Ring." },

  // --- Zeit & Kalender ---
  { es: "el lunes", de: "der Montag", pos: "noun", level: "A1", topic: "Kalender", ex: "El lunes empieza la semana.", exDe: "Am Montag beginnt die Woche." },
  { es: "el martes", de: "der Dienstag", pos: "noun", level: "A1", topic: "Kalender", ex: "Tengo clase el martes.", exDe: "Am Dienstag habe ich Unterricht." },
  { es: "el miércoles", de: "der Mittwoch", pos: "noun", level: "A1", topic: "Kalender", ex: "El miércoles voy al médico.", exDe: "Am Mittwoch gehe ich zum Arzt." },
  { es: "el jueves", de: "der Donnerstag", pos: "noun", level: "A1", topic: "Kalender", ex: "El jueves salimos a cenar.", exDe: "Am Donnerstag gehen wir essen." },
  { es: "el viernes", de: "der Freitag", pos: "noun", level: "A1", topic: "Kalender", ex: "El viernes empieza el fin de semana.", exDe: "Am Freitag beginnt das Wochenende." },
  { es: "el sábado", de: "der Samstag", pos: "noun", level: "A1", topic: "Kalender", ex: "El sábado dormimos hasta tarde.", exDe: "Am Samstag schlafen wir lange." },
  { es: "el domingo", de: "der Sonntag", pos: "noun", level: "A1", topic: "Kalender", ex: "El domingo visitamos a mis padres.", exDe: "Am Sonntag besuchen wir meine Eltern." },
  { es: "enero", de: "Januar", pos: "noun", level: "A1", topic: "Kalender", ex: "En enero hace mucho frío.", exDe: "Im Januar ist es sehr kalt." },
  { es: "febrero", de: "Februar", pos: "noun", level: "A1", topic: "Kalender", ex: "Su cumpleaños es en febrero.", exDe: "Sein Geburtstag ist im Februar." },
  { es: "marzo", de: "März", pos: "noun", level: "A1", topic: "Kalender", ex: "La primavera empieza en marzo.", exDe: "Der Frühling beginnt im März." },
  { es: "abril", de: "April", pos: "noun", level: "A1", topic: "Kalender", ex: "En abril llueve mucho.", exDe: "Im April regnet es viel." },
  { es: "mayo", de: "Mai", pos: "noun", level: "A1", topic: "Kalender", ex: "Nos casamos en mayo.", exDe: "Wir heiraten im Mai." },
  { es: "junio", de: "Juni", pos: "noun", level: "A1", topic: "Kalender", ex: "El curso termina en junio.", exDe: "Der Kurs endet im Juni." },
  { es: "julio", de: "Juli", pos: "noun", level: "A1", topic: "Kalender", ex: "En julio hace mucho calor.", exDe: "Im Juli ist es sehr heiß." },
  { es: "agosto", de: "August", pos: "noun", level: "A1", topic: "Kalender", ex: "Estoy de vacaciones en agosto.", exDe: "Im August habe ich Urlaub." },
  { es: "septiembre", de: "September", pos: "noun", level: "A1", topic: "Kalender", ex: "Las clases empiezan en septiembre.", exDe: "Der Unterricht beginnt im September." },
  { es: "octubre", de: "Oktober", pos: "noun", level: "A1", topic: "Kalender", ex: "El otoño llega en octubre.", exDe: "Der Herbst kommt im Oktober." },
  { es: "noviembre", de: "November", pos: "noun", level: "A1", topic: "Kalender", ex: "En noviembre los días son cortos.", exDe: "Im November sind die Tage kurz." },
  { es: "diciembre", de: "Dezember", pos: "noun", level: "A1", topic: "Kalender", ex: "Celebramos la Navidad en diciembre.", exDe: "Wir feiern Weihnachten im Dezember." },
  { es: "la primavera", de: "der Frühling", pos: "noun", level: "A1", topic: "Kalender", ex: "Me encanta la primavera.", exDe: "Ich liebe den Frühling." },
  { es: "el verano", de: "der Sommer", pos: "noun", level: "A1", topic: "Kalender", ex: "En verano vamos a la playa.", exDe: "Im Sommer fahren wir an den Strand." },
  { es: "el otoño", de: "der Herbst", pos: "noun", level: "A1", topic: "Kalender", ex: "Las hojas caen en otoño.", exDe: "Im Herbst fallen die Blätter." },
  { es: "el invierno", de: "der Winter", pos: "noun", level: "A1", topic: "Kalender", ex: "En invierno nieva mucho aquí.", exDe: "Im Winter schneit es hier viel." },
  { es: "la noche", de: "die Nacht", pos: "noun", level: "A1", topic: "Kalender", ex: "Trabajo por la noche.", exDe: "Ich arbeite nachts." },
  { es: "el mediodía", de: "der Mittag", pos: "noun", level: "A2", topic: "Kalender", ex: "Comemos al mediodía.", exDe: "Wir essen zu Mittag." },
  { es: "la medianoche", de: "die Mitternacht", pos: "noun", level: "A2", topic: "Kalender", ex: "Volvimos a medianoche.", exDe: "Wir kamen um Mitternacht zurück." },
  { es: "el fin de semana", de: "das Wochenende", pos: "noun", level: "A1", topic: "Kalender", ex: "¿Qué haces el fin de semana?", exDe: "Was machst du am Wochenende?" },
  { es: "la hora", de: "die Stunde|die Uhrzeit", pos: "noun", level: "A1", topic: "Kalender", ex: "¿Qué hora es?", exDe: "Wie spät ist es?" },
  { es: "el minuto", de: "die Minute", pos: "noun", level: "A1", topic: "Kalender", ex: "Vuelvo en un minuto.", exDe: "Ich bin in einer Minute zurück." },
  { es: "el segundo", de: "die Sekunde", pos: "noun", level: "A2", topic: "Kalender", ex: "Espera un segundo, por favor.", exDe: "Warte bitte eine Sekunde." },
  { es: "la fecha", de: "das Datum", pos: "noun", level: "A2", topic: "Kalender", ex: "¿Cuál es la fecha de hoy?", exDe: "Welches Datum haben wir heute?" },
  { es: "el reloj", de: "die Uhr", pos: "noun", level: "A2", topic: "Kalender", ex: "Mi reloj se ha parado.", exDe: "Meine Uhr ist stehen geblieben." },
  { es: "luego", de: "später|dann", pos: "adv", level: "A2", topic: "Zeit", ex: "Nos vemos luego.", exDe: "Wir sehen uns später." },
  { es: "después", de: "danach|nachher", pos: "adv", level: "A2", topic: "Zeit", ex: "Después vamos al cine.", exDe: "Danach gehen wir ins Kino." },
  { es: "todavía", de: "noch", pos: "adv", level: "A2", topic: "Zeit", ex: "Todavía no ha llegado.", exDe: "Er ist noch nicht angekommen." },
  { es: "ya", de: "schon|bereits", pos: "adv", level: "A2", topic: "Zeit", ex: "Ya he terminado.", exDe: "Ich bin schon fertig." },
  { es: "mientras", de: "während", pos: "adv", level: "B1", topic: "Zeit", ex: "Escucho música mientras trabajo.", exDe: "Ich höre Musik, während ich arbeite." },
  { es: "entonces", de: "dann|also", pos: "adv", level: "A2", topic: "Zeit", ex: "Entonces, ¿qué hacemos?", exDe: "Was machen wir also?" },
  { es: "pronto", de: "bald", pos: "adv", level: "A2", topic: "Zeit", ex: "Vuelvo pronto.", exDe: "Ich komme bald zurück." },
  { es: "tarde", de: "spät", pos: "adv", level: "A1", topic: "Zeit", ex: "Llegamos tarde a la fiesta.", exDe: "Wir kamen spät zur Party." },

  // --- Pronomen & Fragewörter ---
  { es: "yo", de: "ich", pos: "pron", level: "A1", topic: "Pronomen", ex: "Yo vivo en Berlín.", exDe: "Ich wohne in Berlin." },
  { es: "tú", de: "du", pos: "pron", level: "A1", topic: "Pronomen", ex: "¿Tú de dónde eres?", exDe: "Woher kommst du?" },
  { es: "él", de: "er", pos: "pron", level: "A1", topic: "Pronomen", ex: "Él trabaja en un banco.", exDe: "Er arbeitet in einer Bank." },
  { es: "ella", de: "sie (Sg.)", pos: "pron", level: "A1", topic: "Pronomen", ex: "Ella estudia arquitectura.", exDe: "Sie studiert Architektur." },
  { es: "nosotros", de: "wir", pos: "pron", level: "A1", topic: "Pronomen", ex: "Nosotros vamos al parque.", exDe: "Wir gehen in den Park." },
  { es: "ellos", de: "sie (Pl.)", pos: "pron", level: "A1", topic: "Pronomen", ex: "Ellos llegan mañana.", exDe: "Sie kommen morgen an." },
  { es: "usted", de: "Sie (höflich)", pos: "pron", level: "A2", topic: "Pronomen", ex: "¿Cómo está usted?", exDe: "Wie geht es Ihnen?" },
  { es: "qué", de: "was", pos: "pron", level: "A1", topic: "Fragewörter", ex: "¿Qué quieres comer?", exDe: "Was möchtest du essen?" },
  { es: "quién", de: "wer", pos: "pron", level: "A1", topic: "Fragewörter", ex: "¿Quién es esa persona?", exDe: "Wer ist diese Person?" },
  { es: "cuándo", de: "wann", pos: "adv", level: "A1", topic: "Fragewörter", ex: "¿Cuándo llegas?", exDe: "Wann kommst du an?" },
  { es: "dónde", de: "wo", pos: "adv", level: "A1", topic: "Fragewörter", ex: "¿Dónde vives?", exDe: "Wo wohnst du?" },
  { es: "cómo", de: "wie", pos: "adv", level: "A1", topic: "Fragewörter", ex: "¿Cómo te llamas?", exDe: "Wie heißt du?" },
  { es: "por qué", de: "warum", pos: "adv", level: "A1", topic: "Fragewörter", ex: "¿Por qué llegas tarde?", exDe: "Warum kommst du zu spät?" },
  { es: "cuál", de: "welcher|welche|welches", pos: "pron", level: "A2", topic: "Fragewörter", ex: "¿Cuál prefieres?", exDe: "Welches bevorzugst du?" },
  { es: "cuánto", de: "wie viel", pos: "pron", level: "A1", topic: "Fragewörter", ex: "¿Cuánto cuesta?", exDe: "Wie viel kostet das?" },

  // --- Präpositionen & Konjunktionen ---
  { es: "en", de: "in|an|auf", pos: "prep", level: "A1", topic: "Präpositionen", ex: "Vivo en Madrid.", exDe: "Ich wohne in Madrid." },
  { es: "con", de: "mit", pos: "prep", level: "A1", topic: "Präpositionen", ex: "Voy con mis amigos.", exDe: "Ich gehe mit meinen Freunden." },
  { es: "sin", de: "ohne", pos: "prep", level: "A1", topic: "Präpositionen", ex: "Café sin azúcar, por favor.", exDe: "Kaffee ohne Zucker, bitte." },
  { es: "para", de: "für|um zu", pos: "prep", level: "A1", topic: "Präpositionen", ex: "Este regalo es para ti.", exDe: "Dieses Geschenk ist für dich." },
  { es: "sobre", de: "über|auf", pos: "prep", level: "A2", topic: "Präpositionen", ex: "El libro está sobre la mesa.", exDe: "Das Buch liegt auf dem Tisch." },
  { es: "bajo", de: "unter", pos: "prep", level: "A2", topic: "Präpositionen", ex: "El gato duerme bajo la mesa.", exDe: "Die Katze schläft unter dem Tisch." },
  { es: "entre", de: "zwischen", pos: "prep", level: "A2", topic: "Präpositionen", ex: "El banco está entre la farmacia y el bar.", exDe: "Die Bank ist zwischen der Apotheke und der Bar." },
  { es: "desde", de: "seit|von … an", pos: "prep", level: "A2", topic: "Präpositionen", ex: "Vivo aquí desde 2019.", exDe: "Ich wohne seit 2019 hier." },
  { es: "hasta", de: "bis", pos: "prep", level: "A2", topic: "Präpositionen", ex: "Trabajo hasta las seis.", exDe: "Ich arbeite bis sechs." },
  { es: "durante", de: "während", pos: "prep", level: "B1", topic: "Präpositionen", ex: "No hables durante la película.", exDe: "Sprich nicht während des Films." },
  { es: "contra", de: "gegen", pos: "prep", level: "B1", topic: "Präpositionen", ex: "Jugamos contra el equipo local.", exDe: "Wir spielen gegen die einheimische Mannschaft." },
  { es: "según", de: "laut|gemäß", pos: "prep", level: "B1", topic: "Präpositionen", ex: "Según el pronóstico, va a llover.", exDe: "Laut Vorhersage wird es regnen." },
  { es: "porque", de: "weil", pos: "conj", level: "A1", topic: "Konjunktionen", ex: "No salgo porque llueve.", exDe: "Ich gehe nicht raus, weil es regnet." },
  { es: "aunque", de: "obwohl", pos: "conj", level: "B1", topic: "Konjunktionen", ex: "Salimos aunque hace frío.", exDe: "Wir gehen raus, obwohl es kalt ist." },
  { es: "si", de: "wenn|falls", pos: "conj", level: "A2", topic: "Konjunktionen", ex: "Si llueve, nos quedamos en casa.", exDe: "Wenn es regnet, bleiben wir zu Hause." },
  { es: "mientras que", de: "während|wohingegen", pos: "conj", level: "B1", topic: "Konjunktionen", ex: "Él cocina mientras que yo limpio.", exDe: "Er kocht, während ich putze." },

  // --- Körper & Gesundheit ---
  { es: "el cuerpo", de: "der Körper", pos: "noun", level: "A2", topic: "Körper", ex: "El ejercicio es bueno para el cuerpo.", exDe: "Sport ist gut für den Körper." },
  { es: "la cabeza", de: "der Kopf", pos: "noun", level: "A1", topic: "Körper", ex: "Me duele la cabeza.", exDe: "Mir tut der Kopf weh." },
  { es: "la cara", de: "das Gesicht", pos: "noun", level: "A2", topic: "Körper", ex: "Tiene una cara muy simpática.", exDe: "Er hat ein sehr sympathisches Gesicht." },
  { es: "el ojo", de: "das Auge", pos: "noun", level: "A1", topic: "Körper", ex: "Tiene los ojos verdes.", exDe: "Sie hat grüne Augen." },
  { es: "la nariz", de: "die Nase", pos: "noun", level: "A2", topic: "Körper", ex: "Le sangra la nariz.", exDe: "Seine Nase blutet." },
  { es: "la boca", de: "der Mund", pos: "noun", level: "A2", topic: "Körper", ex: "Abre la boca, por favor.", exDe: "Öffne bitte den Mund." },
  { es: "la oreja", de: "das Ohr", pos: "noun", level: "A2", topic: "Körper", ex: "Le duele la oreja izquierda.", exDe: "Sein linkes Ohr tut weh." },
  { es: "el pelo", de: "die Haare", pos: "noun", level: "A1", topic: "Körper", ex: "Tiene el pelo largo.", exDe: "Sie hat lange Haare." },
  { es: "el brazo", de: "der Arm", pos: "noun", level: "A2", topic: "Körper", ex: "Se rompió el brazo esquiando.", exDe: "Er hat sich beim Skifahren den Arm gebrochen." },
  { es: "la mano", de: "die Hand", pos: "noun", level: "A1", topic: "Körper", ex: "Dame la mano.", exDe: "Gib mir die Hand." },
  { es: "el dedo", de: "der Finger", pos: "noun", level: "A2", topic: "Körper", ex: "Me corté el dedo cocinando.", exDe: "Ich habe mir beim Kochen in den Finger geschnitten." },
  { es: "la pierna", de: "das Bein", pos: "noun", level: "A2", topic: "Körper", ex: "Tiene la pierna hinchada.", exDe: "Sein Bein ist geschwollen." },
  { es: "el pie", de: "der Fuß", pos: "noun", level: "A1", topic: "Körper", ex: "Vamos a pie al centro.", exDe: "Wir gehen zu Fuß ins Zentrum." },
  { es: "la espalda", de: "der Rücken", pos: "noun", level: "A2", topic: "Körper", ex: "Me duele la espalda de estar sentado.", exDe: "Mein Rücken tut vom Sitzen weh." },
  { es: "el estómago", de: "der Magen", pos: "noun", level: "A2", topic: "Körper", ex: "Me duele el estómago.", exDe: "Mir tut der Magen weh." },
  { es: "el corazón", de: "das Herz", pos: "noun", level: "A2", topic: "Körper", ex: "Su corazón late muy rápido.", exDe: "Sein Herz schlägt sehr schnell." },
  { es: "el diente", de: "der Zahn", pos: "noun", level: "A2", topic: "Körper", ex: "Tengo que ir al dentista, me duele un diente.", exDe: "Ich muss zum Zahnarzt, mir tut ein Zahn weh." },
  { es: "la piel", de: "die Haut", pos: "noun", level: "B1", topic: "Körper", ex: "Tiene la piel muy sensible.", exDe: "Ihre Haut ist sehr empfindlich." },
  { es: "la salud", de: "die Gesundheit", pos: "noun", level: "A2", topic: "Gesundheit", ex: "La salud es lo más importante.", exDe: "Die Gesundheit ist das Wichtigste." },
  { es: "la enfermedad", de: "die Krankheit", pos: "noun", level: "B1", topic: "Gesundheit", ex: "Se recuperó de la enfermedad.", exDe: "Er hat sich von der Krankheit erholt." },
  { es: "el médico", de: "der Arzt", pos: "noun", level: "A1", topic: "Gesundheit", ex: "Tengo cita con el médico.", exDe: "Ich habe einen Termin beim Arzt." },
  { es: "el hospital", de: "das Krankenhaus", pos: "noun", level: "A2", topic: "Gesundheit", ex: "La llevaron al hospital en ambulancia.", exDe: "Sie wurde mit dem Krankenwagen ins Krankenhaus gebracht." },
  { es: "la farmacia", de: "die Apotheke", pos: "noun", level: "A2", topic: "Gesundheit", ex: "La farmacia está a la vuelta de la esquina.", exDe: "Die Apotheke ist gleich um die Ecke." },
  { es: "la medicina", de: "das Medikament|die Medizin", pos: "noun", level: "A2", topic: "Gesundheit", ex: "Tienes que tomar esta medicina tres veces al día.", exDe: "Du musst dieses Medikament dreimal täglich nehmen." },
  { es: "la fiebre", de: "das Fieber", pos: "noun", level: "A2", topic: "Gesundheit", ex: "Tiene mucha fiebre.", exDe: "Er hat hohes Fieber." },
  { es: "la tos", de: "der Husten", pos: "noun", level: "B1", topic: "Gesundheit", ex: "Tengo tos desde ayer.", exDe: "Ich habe seit gestern Husten." },
  { es: "el dolor", de: "der Schmerz", pos: "noun", level: "A2", topic: "Gesundheit", ex: "Siento un dolor fuerte en la espalda.", exDe: "Ich habe starke Schmerzen im Rücken." },
  { es: "la receta", de: "das Rezept", pos: "noun", level: "B1", topic: "Gesundheit", ex: "Necesito una receta para este medicamento.", exDe: "Ich brauche ein Rezept für dieses Medikament." },
  { es: "grave", de: "ernst|schwerwiegend", pos: "adj", level: "B1", topic: "Gesundheit", ex: "No es nada grave.", exDe: "Es ist nichts Ernstes." },
  { es: "sano", de: "gesund", pos: "adj", level: "A2", topic: "Gesundheit", ex: "Come de forma sana.", exDe: "Sie ernährt sich gesund." },
  { es: "enfermo", de: "krank", pos: "adj", level: "A2", topic: "Gesundheit", ex: "Hoy estoy enfermo.", exDe: "Heute bin ich krank." },
  { es: "doler", de: "wehtun|schmerzen", pos: "verb", level: "A2", topic: "Gesundheit", ex: "Me duele la garganta.", exDe: "Mein Hals tut weh." },
  { es: "curar", de: "heilen", pos: "verb", level: "B1", topic: "Gesundheit", ex: "Este jarabe cura la tos.", exDe: "Dieser Sirup heilt den Husten." },
  { es: "romperse", de: "sich brechen", pos: "verb", level: "B1", topic: "Gesundheit", ex: "Se rompió la pierna esquiando.", exDe: "Er hat sich beim Skifahren das Bein gebrochen." },

  // --- Kleidung ---
  { es: "la ropa", de: "die Kleidung", pos: "noun", level: "A1", topic: "Kleidung", ex: "Necesito comprar ropa de invierno.", exDe: "Ich muss Winterkleidung kaufen." },
  { es: "la camisa", de: "das Hemd", pos: "noun", level: "A2", topic: "Kleidung", ex: "Lleva una camisa blanca.", exDe: "Er trägt ein weißes Hemd." },
  { es: "la camiseta", de: "das T-Shirt", pos: "noun", level: "A2", topic: "Kleidung", ex: "Compré una camiseta nueva.", exDe: "Ich habe ein neues T-Shirt gekauft." },
  { es: "el pantalón", de: "die Hose", pos: "noun", level: "A2", topic: "Kleidung", ex: "Estos pantalones me quedan grandes.", exDe: "Diese Hose ist mir zu groß." },
  { es: "el vestido", de: "das Kleid", pos: "noun", level: "A2", topic: "Kleidung", ex: "Se compró un vestido para la boda.", exDe: "Sie hat sich ein Kleid für die Hochzeit gekauft." },
  { es: "la falda", de: "der Rock", pos: "noun", level: "A2", topic: "Kleidung", ex: "Lleva una falda larga.", exDe: "Sie trägt einen langen Rock." },
  { es: "los zapatos", de: "die Schuhe", pos: "noun", level: "A1", topic: "Kleidung", ex: "Necesito zapatos nuevos.", exDe: "Ich brauche neue Schuhe." },
  { es: "la chaqueta", de: "die Jacke", pos: "noun", level: "A2", topic: "Kleidung", ex: "Ponte la chaqueta, hace frío.", exDe: "Zieh die Jacke an, es ist kalt." },
  { es: "el abrigo", de: "der Mantel", pos: "noun", level: "A2", topic: "Kleidung", ex: "En invierno llevo abrigo.", exDe: "Im Winter trage ich einen Mantel." },
  { es: "el sombrero", de: "der Hut", pos: "noun", level: "B1", topic: "Kleidung", ex: "Lleva un sombrero de paja.", exDe: "Er trägt einen Strohhut." },
  { es: "las gafas", de: "die Brille", pos: "noun", level: "A2", topic: "Kleidung", ex: "Necesito gafas para leer.", exDe: "Ich brauche eine Brille zum Lesen." },
  { es: "el bolso", de: "die Tasche|die Handtasche", pos: "noun", level: "A2", topic: "Kleidung", ex: "Dejó el bolso en el coche.", exDe: "Sie hat die Tasche im Auto gelassen." },
  { es: "llevar", de: "tragen", pos: "verb", level: "A2", topic: "Kleidung", ex: "Hoy lleva un vestido rojo.", exDe: "Heute trägt sie ein rotes Kleid." },
  { es: "vestirse", de: "sich anziehen", pos: "verb", level: "A2", topic: "Kleidung", ex: "Me visto rápido por la mañana.", exDe: "Ich ziehe mich morgens schnell an." },
  { es: "quitarse", de: "ausziehen|ablegen", pos: "verb", level: "A2", topic: "Kleidung", ex: "Se quitó los zapatos al entrar.", exDe: "Er zog beim Reingehen die Schuhe aus." },

  // --- Wetter ---
  { es: "el tiempo", de: "das Wetter", pos: "noun", level: "A1", topic: "Wetter", ex: "¿Qué tiempo hace hoy?", exDe: "Wie ist das Wetter heute?" },
  { es: "el sol", de: "die Sonne", pos: "noun", level: "A1", topic: "Wetter", ex: "Hace mucho sol hoy.", exDe: "Heute scheint viel die Sonne." },
  { es: "la lluvia", de: "der Regen", pos: "noun", level: "A2", topic: "Wetter", ex: "La lluvia no para desde ayer.", exDe: "Der Regen hört seit gestern nicht auf." },
  { es: "la nieve", de: "der Schnee", pos: "noun", level: "A2", topic: "Wetter", ex: "La nieve cubre las montañas.", exDe: "Schnee bedeckt die Berge." },
  { es: "el viento", de: "der Wind", pos: "noun", level: "A2", topic: "Wetter", ex: "Hace mucho viento en la costa.", exDe: "An der Küste weht viel Wind." },
  { es: "la nube", de: "die Wolke", pos: "noun", level: "B1", topic: "Wetter", ex: "El cielo está lleno de nubes.", exDe: "Der Himmel ist voller Wolken." },
  { es: "la tormenta", de: "das Gewitter|der Sturm", pos: "noun", level: "B1", topic: "Wetter", ex: "Se acerca una tormenta.", exDe: "Ein Gewitter zieht auf." },
  { es: "el calor", de: "die Hitze", pos: "noun", level: "A2", topic: "Wetter", ex: "No aguanto este calor.", exDe: "Ich halte diese Hitze nicht aus." },
  { es: "el frío", de: "die Kälte", pos: "noun", level: "A1", topic: "Wetter", ex: "Tengo mucho frío.", exDe: "Mir ist sehr kalt." },
  { es: "llover", de: "regnen", pos: "verb", level: "A1", topic: "Wetter", ex: "Está lloviendo mucho.", exDe: "Es regnet stark." },
  { es: "nevar", de: "schneien", pos: "verb", level: "A2", topic: "Wetter", ex: "Nevó toda la noche.", exDe: "Es hat die ganze Nacht geschneit." },
  { es: "soleado", de: "sonnig", pos: "adj", level: "A2", topic: "Wetter", ex: "Mañana será un día soleado.", exDe: "Morgen wird ein sonniger Tag." },
  { es: "nublado", de: "bewölkt", pos: "adj", level: "A2", topic: "Wetter", ex: "El cielo está nublado.", exDe: "Der Himmel ist bewölkt." },
  { es: "húmedo", de: "feucht", pos: "adj", level: "B1", topic: "Wetter", ex: "El clima aquí es muy húmedo.", exDe: "Das Klima hier ist sehr feucht." },

  // --- Familie & Menschen erweitert ---
  { es: "el padre", de: "der Vater", pos: "noun", level: "A1", topic: "Menschen", ex: "Mi padre trabaja de ingeniero.", exDe: "Mein Vater arbeitet als Ingenieur." },
  { es: "la madre", de: "die Mutter", pos: "noun", level: "A1", topic: "Menschen", ex: "Mi madre cocina muy bien.", exDe: "Meine Mutter kocht sehr gut." },
  { es: "los padres", de: "die Eltern", pos: "noun", level: "A1", topic: "Menschen", ex: "Mis padres viven en el campo.", exDe: "Meine Eltern leben auf dem Land." },
  { es: "el abuelo", de: "der Großvater", pos: "noun", level: "A1", topic: "Menschen", ex: "Mi abuelo cuenta muy buenas historias.", exDe: "Mein Großvater erzählt sehr gute Geschichten." },
  { es: "la abuela", de: "die Großmutter", pos: "noun", level: "A1", topic: "Menschen", ex: "Mi abuela hace la mejor tarta.", exDe: "Meine Großmutter macht den besten Kuchen." },
  { es: "el tío", de: "der Onkel", pos: "noun", level: "A2", topic: "Menschen", ex: "Mi tío vive en Argentina.", exDe: "Mein Onkel lebt in Argentinien." },
  { es: "la tía", de: "die Tante", pos: "noun", level: "A2", topic: "Menschen", ex: "Mi tía nos visita cada verano.", exDe: "Meine Tante besucht uns jeden Sommer." },
  { es: "el primo", de: "der Cousin", pos: "noun", level: "A2", topic: "Menschen", ex: "Mi primo estudia en Barcelona.", exDe: "Mein Cousin studiert in Barcelona." },
  { es: "el marido", de: "der Ehemann", pos: "noun", level: "A2", topic: "Menschen", ex: "Su marido trabaja en el extranjero.", exDe: "Ihr Ehemann arbeitet im Ausland." },
  { es: "la esposa", de: "die Ehefrau", pos: "noun", level: "A2", topic: "Menschen", ex: "Su esposa es profesora.", exDe: "Seine Ehefrau ist Lehrerin." },
  { es: "el novio", de: "der Freund|der Verlobte", pos: "noun", level: "A2", topic: "Menschen", ex: "Voy a cenar con mi novio.", exDe: "Ich gehe mit meinem Freund essen." },
  { es: "la persona", de: "die Person", pos: "noun", level: "A1", topic: "Menschen", ex: "Es una persona muy amable.", exDe: "Er ist eine sehr freundliche Person." },
  { es: "la gente", de: "die Leute", pos: "noun", level: "A1", topic: "Menschen", ex: "Había mucha gente en la calle.", exDe: "Es waren viele Leute auf der Straße." },
  { es: "el bebé", de: "das Baby", pos: "noun", level: "A2", topic: "Menschen", ex: "El bebé duerme toda la noche.", exDe: "Das Baby schläft die ganze Nacht." },
  { es: "el adulto", de: "der Erwachsene", pos: "noun", level: "B1", topic: "Menschen", ex: "El museo es gratis para adultos mayores.", exDe: "Das Museum ist für Senioren kostenlos." },

  // --- Tiere ---
  { es: "el perro", de: "der Hund", pos: "noun", level: "A1", topic: "Tiere", ex: "El perro duerme en el jardín.", exDe: "Der Hund schläft im Garten." },
  { es: "el gato", de: "die Katze", pos: "noun", level: "A1", topic: "Tiere", ex: "El gato caza ratones.", exDe: "Die Katze jagt Mäuse." },
  { es: "el pájaro", de: "der Vogel", pos: "noun", level: "A2", topic: "Tiere", ex: "Los pájaros cantan por la mañana.", exDe: "Die Vögel singen am Morgen." },
  { es: "el caballo", de: "das Pferd", pos: "noun", level: "A2", topic: "Tiere", ex: "Le encanta montar a caballo.", exDe: "Sie reitet sehr gerne." },
  { es: "la vaca", de: "die Kuh", pos: "noun", level: "A2", topic: "Tiere", ex: "Las vacas pastan en el campo.", exDe: "Die Kühe weiden auf dem Feld." },
  { es: "el pez", de: "der Fisch (lebendig)", pos: "noun", level: "A2", topic: "Tiere", ex: "Hay muchos peces en este río.", exDe: "In diesem Fluss gibt es viele Fische." },
  { es: "el animal", de: "das Tier", pos: "noun", level: "A1", topic: "Tiere", ex: "Es un animal muy tranquilo.", exDe: "Es ist ein sehr ruhiges Tier." },

  // --- Natur ---
  { es: "el árbol", de: "der Baum", pos: "noun", level: "A1", topic: "Natur", ex: "Hay un árbol grande en el jardín.", exDe: "Im Garten steht ein großer Baum." },
  { es: "la flor", de: "die Blume", pos: "noun", level: "A1", topic: "Natur", ex: "Le regalé unas flores.", exDe: "Ich habe ihr Blumen geschenkt." },
  { es: "el mar", de: "das Meer", pos: "noun", level: "A1", topic: "Natur", ex: "El mar está muy tranquilo hoy.", exDe: "Das Meer ist heute sehr ruhig." },
  { es: "la montaña", de: "der Berg", pos: "noun", level: "A1", topic: "Natur", ex: "Vamos a subir esa montaña.", exDe: "Wir werden auf diesen Berg steigen." },
  { es: "el río", de: "der Fluss", pos: "noun", level: "A2", topic: "Natur", ex: "El río pasa por el centro de la ciudad.", exDe: "Der Fluss fließt durch das Stadtzentrum." },
  { es: "el bosque", de: "der Wald", pos: "noun", level: "A2", topic: "Natur", ex: "Paseamos por el bosque.", exDe: "Wir spazieren durch den Wald." },
  { es: "el campo", de: "das Land|das Feld", pos: "noun", level: "A2", topic: "Natur", ex: "Mis abuelos viven en el campo.", exDe: "Meine Großeltern leben auf dem Land." },
  { es: "el cielo", de: "der Himmel", pos: "noun", level: "A2", topic: "Natur", ex: "El cielo está despejado.", exDe: "Der Himmel ist klar." },
  { es: "la playa", de: "der Strand", pos: "noun", level: "A1", topic: "Natur", ex: "Pasamos el día en la playa.", exDe: "Wir haben den Tag am Strand verbracht." },
  { es: "la isla", de: "die Insel", pos: "noun", level: "B1", topic: "Natur", ex: "Vamos a pasar el verano en una isla.", exDe: "Wir verbringen den Sommer auf einer Insel." },
  { es: "la piedra", de: "der Stein", pos: "noun", level: "B1", topic: "Natur", ex: "Tropezó con una piedra.", exDe: "Er stolperte über einen Stein." },

  // --- Essen & Küche erweitert ---
  { es: "el arroz", de: "der Reis", pos: "noun", level: "A2", topic: "Essen", ex: "El arroz se sirve con pollo.", exDe: "Der Reis wird mit Hähnchen serviert." },
  { es: "la sopa", de: "die Suppe", pos: "noun", level: "A2", topic: "Essen", ex: "La sopa está muy caliente.", exDe: "Die Suppe ist sehr heiß." },
  { es: "la ensalada", de: "der Salat", pos: "noun", level: "A2", topic: "Essen", ex: "Pido una ensalada de tomate.", exDe: "Ich bestelle einen Tomatensalat." },
  { es: "el huevo", de: "das Ei", pos: "noun", level: "A1", topic: "Essen", ex: "Desayuno un huevo cada mañana.", exDe: "Ich frühstücke jeden Morgen ein Ei." },
  { es: "el azúcar", de: "der Zucker", pos: "noun", level: "A2", topic: "Essen", ex: "No tomo azúcar en el café.", exDe: "Ich nehme keinen Zucker in den Kaffee." },
  { es: "la sal", de: "das Salz", pos: "noun", level: "A2", topic: "Essen", ex: "Falta sal en la sopa.", exDe: "Der Suppe fehlt Salz." },
  { es: "el aceite", de: "das Öl", pos: "noun", level: "A2", topic: "Essen", ex: "Usa aceite de oliva para cocinar.", exDe: "Er benutzt Olivenöl zum Kochen." },
  { es: "la fruta", de: "das Obst", pos: "noun", level: "A1", topic: "Essen", ex: "Como fruta todos los días.", exDe: "Ich esse jeden Tag Obst." },
  { es: "la verdura", de: "das Gemüse", pos: "noun", level: "A1", topic: "Essen", ex: "Las verduras son importantes para la salud.", exDe: "Gemüse ist wichtig für die Gesundheit." },
  { es: "la patata", de: "die Kartoffel", pos: "noun", level: "A2", topic: "Essen", ex: "Cociné patatas al horno.", exDe: "Ich habe Ofenkartoffeln gemacht." },
  { es: "la cebolla", de: "die Zwiebel", pos: "noun", level: "A2", topic: "Essen", ex: "Corta la cebolla en trozos pequeños.", exDe: "Schneide die Zwiebel in kleine Stücke." },
  { es: "el tomate", de: "die Tomate", pos: "noun", level: "A2", topic: "Essen", ex: "La salsa lleva tomate fresco.", exDe: "Die Soße enthält frische Tomaten." },
  { es: "el ajo", de: "der Knoblauch", pos: "noun", level: "B1", topic: "Essen", ex: "Añade un diente de ajo.", exDe: "Füg eine Knoblauchzehe hinzu." },
  { es: "el limón", de: "die Zitrone", pos: "noun", level: "A2", topic: "Essen", ex: "Le pongo limón al pescado.", exDe: "Ich gebe Zitrone auf den Fisch." },
  { es: "el postre", de: "die Nachspeise|der Nachtisch", pos: "noun", level: "A2", topic: "Essen", ex: "¿Qué hay de postre?", exDe: "Was gibt es als Nachtisch?" },
  { es: "el almuerzo", de: "das Mittagessen", pos: "noun", level: "A2", topic: "Essen", ex: "El almuerzo es a la una.", exDe: "Das Mittagessen ist um eins." },
  { es: "la cena", de: "das Abendessen", pos: "noun", level: "A1", topic: "Essen", ex: "La cena está lista.", exDe: "Das Abendessen ist fertig." },
  { es: "el restaurante", de: "das Restaurant", pos: "noun", level: "A1", topic: "Essen", ex: "Cenamos en un restaurante italiano.", exDe: "Wir haben in einem italienischen Restaurant gegessen." },
  { es: "el camarero", de: "der Kellner", pos: "noun", level: "A2", topic: "Essen", ex: "El camarero nos trajo la carta.", exDe: "Der Kellner brachte uns die Speisekarte." },
  { es: "la carta", de: "die Speisekarte", pos: "noun", level: "A2", topic: "Essen", ex: "¿Nos trae la carta, por favor?", exDe: "Bringen Sie uns bitte die Speisekarte?" },
  { es: "el plato", de: "der Teller|das Gericht", pos: "noun", level: "A1", topic: "Essen", ex: "Este plato lleva mucho ajo.", exDe: "Dieses Gericht enthält viel Knoblauch." },
  { es: "el vaso", de: "das Glas", pos: "noun", level: "A2", topic: "Essen", ex: "Trae dos vasos de agua.", exDe: "Bring zwei Gläser Wasser." },
  { es: "la taza", de: "die Tasse", pos: "noun", level: "A2", topic: "Essen", ex: "Tomo una taza de café por la mañana.", exDe: "Ich trinke morgens eine Tasse Kaffee." },
  { es: "el tenedor", de: "die Gabel", pos: "noun", level: "B1", topic: "Essen", ex: "Falta un tenedor en la mesa.", exDe: "Auf dem Tisch fehlt eine Gabel." },
  { es: "el cuchillo", de: "das Messer", pos: "noun", level: "B1", topic: "Essen", ex: "Necesito un cuchillo para cortar el pan.", exDe: "Ich brauche ein Messer, um das Brot zu schneiden." },
  { es: "la cuchara", de: "der Löffel", pos: "noun", level: "B1", topic: "Essen", ex: "Come la sopa con cuchara.", exDe: "Er isst die Suppe mit einem Löffel." },
  { es: "el vino", de: "der Wein", pos: "noun", level: "A2", topic: "Essen", ex: "Pedimos una botella de vino tinto.", exDe: "Wir haben eine Flasche Rotwein bestellt." },
  { es: "la cerveza", de: "das Bier", pos: "noun", level: "A2", topic: "Essen", ex: "Tomamos una cerveza en la terraza.", exDe: "Wir tranken ein Bier auf der Terrasse." },
  { es: "el zumo", de: "der Saft", pos: "noun", level: "A2", topic: "Essen", ex: "Prefiero zumo de naranja natural.", exDe: "Ich bevorzuge frisch gepressten Orangensaft." },
  { es: "el café", de: "der Kaffee", pos: "noun", level: "A1", topic: "Essen", ex: "¿Quieres un café?", exDe: "Möchtest du einen Kaffee?" },
  { es: "el té", de: "der Tee", pos: "noun", level: "A1", topic: "Essen", ex: "Por la tarde tomo té.", exDe: "Nachmittags trinke ich Tee." },
  { es: "el azúcar moreno", de: "der braune Zucker", pos: "noun", level: "B1", topic: "Essen", ex: "Usa azúcar moreno para el postre.", exDe: "Er benutzt braunen Zucker für den Nachtisch." },
  { es: "cocinar", de: "kochen", pos: "verb", level: "A1", topic: "Verben", ex: "Me gusta cocinar los domingos.", exDe: "Ich koche gerne sonntags." },
  { es: "cortar", de: "schneiden", pos: "verb", level: "A2", topic: "Verben", ex: "Corta las verduras en trozos.", exDe: "Schneide das Gemüse in Stücke." },
  { es: "freír", de: "braten|frittieren", pos: "verb", level: "B1", topic: "Verben", ex: "Freímos el pescado en aceite.", exDe: "Wir braten den Fisch in Öl." },
  { es: "hervir", de: "kochen (Wasser)", pos: "verb", level: "B1", topic: "Verben", ex: "Hierve el agua antes de añadir la pasta.", exDe: "Koche das Wasser, bevor du die Pasta hinzufügst." },
  { es: "añadir", de: "hinzufügen", pos: "verb", level: "B1", topic: "Verben", ex: "Añade un poco de sal.", exDe: "Füge etwas Salz hinzu." },
  { es: "mezclar", de: "mischen", pos: "verb", level: "B1", topic: "Verben", ex: "Mezcla los ingredientes bien.", exDe: "Vermische die Zutaten gut." },
  { es: "pelar", de: "schälen", pos: "verb", level: "B1", topic: "Verben", ex: "Pela las patatas primero.", exDe: "Schäle zuerst die Kartoffeln." },
  { es: "servir", de: "servieren", pos: "verb", level: "A2", topic: "Verben", ex: "El desayuno se sirve a las ocho.", exDe: "Das Frühstück wird um acht serviert." },
  { es: "pedir", de: "bestellen|bitten", pos: "verb", level: "A2", topic: "Verben", ex: "Voy a pedir la pasta.", exDe: "Ich werde die Pasta bestellen." },
  { es: "reservar", de: "reservieren", pos: "verb", level: "A2", topic: "Verben", ex: "Reservé una mesa para dos.", exDe: "Ich habe einen Tisch für zwei reserviert." },

  // --- Weitere Verben ---
  { es: "poder", de: "können", pos: "verb", level: "A1", topic: "Verben", ex: "¿Puedes ayudarme?", exDe: "Kannst du mir helfen?" },
  { es: "querer", de: "wollen|lieben", pos: "verb", level: "A1", topic: "Verben", ex: "Quiero aprender español.", exDe: "Ich möchte Spanisch lernen." },
  { es: "saber", de: "wissen|können (Fähigkeit)", pos: "verb", level: "A1", topic: "Verben", ex: "No sé la respuesta.", exDe: "Ich weiß die Antwort nicht." },
  { es: "conocer", de: "kennen", pos: "verb", level: "A1", topic: "Verben", ex: "Conozco a tu hermana.", exDe: "Ich kenne deine Schwester." },
  { es: "ver", de: "sehen", pos: "verb", level: "A1", topic: "Verben", ex: "Vemos una película esta noche.", exDe: "Wir schauen uns heute Abend einen Film an." },
  { es: "dar", de: "geben", pos: "verb", level: "A1", topic: "Verben", ex: "Te doy mi número de teléfono.", exDe: "Ich gebe dir meine Telefonnummer." },
  { es: "poner", de: "legen|stellen|setzen", pos: "verb", level: "A1", topic: "Verben", ex: "Pon el libro en la mesa.", exDe: "Leg das Buch auf den Tisch." },
  { es: "salir", de: "hinausgehen|ausgehen", pos: "verb", level: "A1", topic: "Verben", ex: "Salgo de casa a las ocho.", exDe: "Ich verlasse um acht das Haus." },
  { es: "venir", de: "kommen", pos: "verb", level: "A1", topic: "Verben", ex: "¿Vienes a la fiesta?", exDe: "Kommst du zur Party?" },
  { es: "llegar", de: "ankommen", pos: "verb", level: "A1", topic: "Verben", ex: "El tren llega a las diez.", exDe: "Der Zug kommt um zehn an." },
  { es: "volver", de: "zurückkommen|zurückkehren", pos: "verb", level: "A1", topic: "Verben", ex: "Vuelvo en cinco minutos.", exDe: "Ich bin in fünf Minuten zurück." },
  { es: "empezar", de: "anfangen|beginnen", pos: "verb", level: "A1", topic: "Verben", ex: "La película empieza a las nueve.", exDe: "Der Film beginnt um neun." },
  { es: "terminar", de: "beenden|enden", pos: "verb", level: "A1", topic: "Verben", ex: "Termino el trabajo a las cinco.", exDe: "Ich beende die Arbeit um fünf." },
  { es: "pensar", de: "denken", pos: "verb", level: "A1", topic: "Verben", ex: "Pienso en ti a menudo.", exDe: "Ich denke oft an dich." },
  { es: "creer", de: "glauben", pos: "verb", level: "A1", topic: "Verben", ex: "Creo que tienes razón.", exDe: "Ich glaube, du hast recht." },
  { es: "sentir", de: "fühlen|spüren", pos: "verb", level: "A2", topic: "Verben", ex: "Siento mucho frío.", exDe: "Mir ist sehr kalt." },
  { es: "gustar", de: "gefallen|mögen", pos: "verb", level: "A1", topic: "Verben", ex: "Me gusta mucho esta ciudad.", exDe: "Mir gefällt diese Stadt sehr." },
  { es: "encontrar", de: "finden", pos: "verb", level: "A1", topic: "Verben", ex: "No encuentro las llaves.", exDe: "Ich finde die Schlüssel nicht." },
  { es: "buscar", de: "suchen", pos: "verb", level: "A1", topic: "Verben", ex: "Busco trabajo desde hace un mes.", exDe: "Ich suche seit einem Monat Arbeit." },
  { es: "abrir", de: "öffnen", pos: "verb", level: "A1", topic: "Verben", ex: "Abro la tienda a las nueve.", exDe: "Ich öffne den Laden um neun." },
  { es: "cerrar", de: "schließen", pos: "verb", level: "A1", topic: "Verben", ex: "Cierra la puerta, por favor.", exDe: "Schließ bitte die Tür." },
  { es: "jugar", de: "spielen", pos: "verb", level: "A1", topic: "Verben", ex: "Los niños juegan en el parque.", exDe: "Die Kinder spielen im Park." },
  { es: "ganar", de: "gewinnen|verdienen", pos: "verb", level: "A2", topic: "Verben", ex: "Ganamos el partido de fútbol.", exDe: "Wir haben das Fußballspiel gewonnen." },
  { es: "perder", de: "verlieren", pos: "verb", level: "A2", topic: "Verben", ex: "Perdí las llaves otra vez.", exDe: "Ich habe wieder die Schlüssel verloren." },
  { es: "correr", de: "laufen|rennen", pos: "verb", level: "A1", topic: "Verben", ex: "Corro todas las mañanas.", exDe: "Ich laufe jeden Morgen." },
  { es: "andar", de: "gehen|laufen", pos: "verb", level: "A2", topic: "Verben", ex: "Vamos a andar por la playa.", exDe: "Wir gehen am Strand spazieren." },
  { es: "subir", de: "hochgehen|steigen", pos: "verb", level: "A2", topic: "Verben", ex: "Subimos al tercer piso.", exDe: "Wir gehen in den dritten Stock hoch." },
  { es: "bajar", de: "hinuntergehen|sinken", pos: "verb", level: "A2", topic: "Verben", ex: "Bajamos las escaleras juntos.", exDe: "Wir gehen zusammen die Treppe runter." },
  { es: "entrar", de: "hineingehen|eintreten", pos: "verb", level: "A2", topic: "Verben", ex: "Entra en la sala, por favor.", exDe: "Bitte komm in den Raum herein." },
  { es: "llamar", de: "anrufen|rufen|nennen", pos: "verb", level: "A1", topic: "Verben", ex: "Te llamo esta tarde.", exDe: "Ich rufe dich heute Nachmittag an." },
  { es: "preguntar", de: "fragen", pos: "verb", level: "A1", topic: "Verben", ex: "Voy a preguntar al profesor.", exDe: "Ich werde den Lehrer fragen." },
  { es: "contestar", de: "antworten", pos: "verb", level: "A2", topic: "Verben", ex: "No contestó a mi mensaje.", exDe: "Er hat nicht auf meine Nachricht geantwortet." },
  { es: "explicar", de: "erklären", pos: "verb", level: "A2", topic: "Verben", ex: "¿Puedes explicarme esto?", exDe: "Kannst du mir das erklären?" },
  { es: "mostrar", de: "zeigen", pos: "verb", level: "A2", topic: "Verben", ex: "Muéstrame tus fotos.", exDe: "Zeig mir deine Fotos." },
  { es: "decidir", de: "entscheiden", pos: "verb", level: "A2", topic: "Verben", ex: "Todavía no he decidido.", exDe: "Ich habe mich noch nicht entschieden." },
  { es: "cambiar", de: "ändern|wechseln", pos: "verb", level: "A2", topic: "Verben", ex: "Quiero cambiar de trabajo.", exDe: "Ich möchte den Job wechseln." },
  { es: "necesitar", de: "brauchen", pos: "verb", level: "A1", topic: "Verben", ex: "Necesito más tiempo.", exDe: "Ich brauche mehr Zeit." },
  { es: "usar", de: "benutzen|verwenden", pos: "verb", level: "A1", topic: "Verben", ex: "Uso el ordenador para trabajar.", exDe: "Ich benutze den Computer zum Arbeiten." },
  { es: "dejar", de: "lassen|verlassen", pos: "verb", level: "A2", topic: "Verben", ex: "Dejé el móvil en casa.", exDe: "Ich habe das Handy zu Hause gelassen." },
  { es: "seguir", de: "folgen|weitermachen", pos: "verb", level: "A2", topic: "Verben", ex: "Sigue todo recto.", exDe: "Geh immer geradeaus weiter." },
  { es: "parecer", de: "scheinen|erscheinen", pos: "verb", level: "A2", topic: "Verben", ex: "Me parece una buena idea.", exDe: "Das scheint mir eine gute Idee zu sein." },
  { es: "ayudar", de: "helfen", pos: "verb", level: "A1", topic: "Verben", ex: "¿Me puedes ayudar con esto?", exDe: "Kannst du mir dabei helfen?" },
  { es: "enseñar", de: "lehren|zeigen", pos: "verb", level: "A2", topic: "Verben", ex: "Enseña español en un instituto.", exDe: "Sie unterrichtet Spanisch an einer Schule." },
  { es: "estudiar", de: "studieren|lernen", pos: "verb", level: "A1", topic: "Verben", ex: "Estudio informática en la universidad.", exDe: "Ich studiere Informatik an der Universität." },
  { es: "dormir", de: "schlafen", pos: "verb", level: "A1", topic: "Verben", ex: "Duermo ocho horas cada noche.", exDe: "Ich schlafe jede Nacht acht Stunden." },
  { es: "despertarse", de: "aufwachen", pos: "verb", level: "A2", topic: "Verben", ex: "Me despierto a las siete.", exDe: "Ich wache um sieben Uhr auf." },
  { es: "levantarse", de: "aufstehen", pos: "verb", level: "A2", topic: "Verben", ex: "Me levanto temprano los lunes.", exDe: "Montags stehe ich früh auf." },
  { es: "ducharse", de: "duschen", pos: "verb", level: "A2", topic: "Verben", ex: "Me ducho antes de desayunar.", exDe: "Ich dusche vor dem Frühstück." },
  { es: "descansar", de: "sich ausruhen", pos: "verb", level: "A2", topic: "Verben", ex: "Necesito descansar un poco.", exDe: "Ich muss mich etwas ausruhen." },
  { es: "limpiar", de: "putzen|reinigen", pos: "verb", level: "A2", topic: "Verben", ex: "Limpio la casa los sábados.", exDe: "Ich putze samstags die Wohnung." },
  { es: "lavar", de: "waschen", pos: "verb", level: "A2", topic: "Verben", ex: "Lavo la ropa dos veces por semana.", exDe: "Ich wasche zweimal pro Woche Wäsche." },
  { es: "abrazar", de: "umarmen", pos: "verb", level: "B1", topic: "Verben", ex: "La abrazó fuerte al despedirse.", exDe: "Er umarmte sie fest zum Abschied." },
  { es: "besar", de: "küssen", pos: "verb", level: "B1", topic: "Verben", ex: "Se besaron al reencontrarse.", exDe: "Sie küssten sich beim Wiedersehen." },
  { es: "reír", de: "lachen", pos: "verb", level: "A2", topic: "Verben", ex: "Nos reímos mucho con esa película.", exDe: "Wir haben bei diesem Film viel gelacht." },
  { es: "llorar", de: "weinen", pos: "verb", level: "A2", topic: "Verben", ex: "El bebé llora por la noche.", exDe: "Das Baby weint nachts." },
  { es: "gritar", de: "schreien", pos: "verb", level: "B1", topic: "Verben", ex: "No hace falta gritar.", exDe: "Du musst nicht schreien." },
  { es: "sonreír", de: "lächeln", pos: "verb", level: "B1", topic: "Verben", ex: "Siempre sonríe al saludar.", exDe: "Er lächelt immer beim Begrüßen." },
  { es: "romper", de: "kaputt machen|zerbrechen", pos: "verb", level: "A2", topic: "Verben", ex: "Se me rompió el vaso.", exDe: "Mir ist das Glas kaputtgegangen." },
  { es: "construir", de: "bauen", pos: "verb", level: "B1", topic: "Verben", ex: "Van a construir un puente nuevo.", exDe: "Sie werden eine neue Brücke bauen." },
  { es: "crear", de: "erschaffen|erstellen", pos: "verb", level: "B1", topic: "Verben", ex: "Creó una empresa hace dos años.", exDe: "Er gründete vor zwei Jahren ein Unternehmen." },
  { es: "mover", de: "bewegen|verschieben", pos: "verb", level: "A2", topic: "Verben", ex: "No pude mover el sofá solo.", exDe: "Ich konnte das Sofa nicht allein verschieben." },
  { es: "tocar", de: "berühren|spielen (Instrument)", pos: "verb", level: "A2", topic: "Verben", ex: "Toca el piano muy bien.", exDe: "Er spielt sehr gut Klavier." },
  { es: "cantar", de: "singen", pos: "verb", level: "A1", topic: "Verben", ex: "Le encanta cantar en la ducha.", exDe: "Sie singt gerne unter der Dusche." },
  { es: "bailar", de: "tanzen", pos: "verb", level: "A2", topic: "Verben", ex: "Bailamos toda la noche.", exDe: "Wir haben die ganze Nacht getanzt." },
  { es: "viajar", de: "reisen", pos: "verb", level: "A1", topic: "Verben", ex: "Me encanta viajar por Sudamérica.", exDe: "Ich reise sehr gerne durch Südamerika." },
  { es: "volar", de: "fliegen", pos: "verb", level: "A2", topic: "Verben", ex: "El avión vuela a diez mil metros.", exDe: "Das Flugzeug fliegt in zehntausend Metern Höhe." },
  { es: "conducir", de: "fahren (Auto)|lenken", pos: "verb", level: "A2", topic: "Verben", ex: "No sabe conducir todavía.", exDe: "Er kann noch nicht Auto fahren." },
  { es: "caminar", de: "gehen|spazieren", pos: "verb", level: "A2", topic: "Verben", ex: "Caminamos una hora por el parque.", exDe: "Wir sind eine Stunde durch den Park gelaufen." },

  // --- Berufe ---
  { es: "el profesor", de: "der Lehrer", pos: "noun", level: "A1", topic: "Berufe", ex: "El profesor explica muy bien.", exDe: "Der Lehrer erklärt sehr gut." },
  { es: "el estudiante", de: "der Student|der Schüler", pos: "noun", level: "A1", topic: "Berufe", ex: "Es estudiante de medicina.", exDe: "Er ist Medizinstudent." },
  { es: "el ingeniero", de: "der Ingenieur", pos: "noun", level: "A2", topic: "Berufe", ex: "Trabaja como ingeniera de software.", exDe: "Sie arbeitet als Softwareingenieurin." },
  { es: "el abogado", de: "der Anwalt", pos: "noun", level: "A2", topic: "Berufe", ex: "Necesito hablar con un abogado.", exDe: "Ich muss mit einem Anwalt sprechen." },
  { es: "el enfermero", de: "der Krankenpfleger", pos: "noun", level: "A2", topic: "Berufe", ex: "El enfermero cuida a los pacientes.", exDe: "Der Krankenpfleger kümmert sich um die Patienten." },
  { es: "el cocinero", de: "der Koch", pos: "noun", level: "A2", topic: "Berufe", ex: "El cocinero preparó un plato delicioso.", exDe: "Der Koch bereitete ein köstliches Gericht zu." },
  { es: "el policía", de: "der Polizist", pos: "noun", level: "A2", topic: "Berufe", ex: "Un policía dirige el tráfico.", exDe: "Ein Polizist regelt den Verkehr." },
  { es: "el periodista", de: "der Journalist", pos: "noun", level: "B1", topic: "Berufe", ex: "Trabaja como periodista en un diario.", exDe: "Er arbeitet als Journalist bei einer Zeitung." },
  { es: "el arquitecto", de: "der Architekt", pos: "noun", level: "B1", topic: "Berufe", ex: "El arquitecto diseñó el nuevo edificio.", exDe: "Der Architekt entwarf das neue Gebäude." },
  { es: "el peluquero", de: "der Friseur", pos: "noun", level: "B1", topic: "Berufe", ex: "Tengo cita con el peluquero.", exDe: "Ich habe einen Termin beim Friseur." },
  { es: "el vendedor", de: "der Verkäufer", pos: "noun", level: "A2", topic: "Berufe", ex: "El vendedor me ayudó a elegir.", exDe: "Der Verkäufer half mir bei der Auswahl." },
  { es: "el científico", de: "der Wissenschaftler", pos: "noun", level: "B1", topic: "Berufe", ex: "Los científicos estudian el cambio climático.", exDe: "Die Wissenschaftler erforschen den Klimawandel." },
  { es: "el artista", de: "der Künstler", pos: "noun", level: "A2", topic: "Berufe", ex: "Es un artista muy conocido.", exDe: "Er ist ein sehr bekannter Künstler." },
  { es: "el gerente", de: "der Geschäftsführer|der Manager", pos: "noun", level: "B1", topic: "Berufe", ex: "El gerente aprobó el proyecto.", exDe: "Der Geschäftsführer genehmigte das Projekt." },
  { es: "el empleado", de: "der Angestellte", pos: "noun", level: "A2", topic: "Berufe", ex: "Es empleado de una empresa grande.", exDe: "Er ist Angestellter eines großen Unternehmens." },

  // --- Technologie & Medien ---
  { es: "el ordenador", de: "der Computer", pos: "noun", level: "A1", topic: "Technologie", ex: "El ordenador se ha bloqueado.", exDe: "Der Computer ist eingefroren." },
  { es: "el móvil", de: "das Handy", pos: "noun", level: "A1", topic: "Technologie", ex: "Se me ha caído el móvil.", exDe: "Mir ist das Handy runtergefallen." },
  { es: "internet", de: "das Internet", pos: "noun", level: "A1", topic: "Technologie", ex: "No funciona internet.", exDe: "Das Internet funktioniert nicht." },
  { es: "la contraseña", de: "das Passwort", pos: "noun", level: "A2", topic: "Technologie", ex: "He olvidado mi contraseña.", exDe: "Ich habe mein Passwort vergessen." },
  { es: "el correo electrónico", de: "die E-Mail", pos: "noun", level: "A2", topic: "Technologie", ex: "Te envío el correo electrónico ahora mismo.", exDe: "Ich schicke dir die E-Mail sofort." },
  { es: "la pantalla", de: "der Bildschirm", pos: "noun", level: "A2", topic: "Technologie", ex: "La pantalla está rota.", exDe: "Der Bildschirm ist kaputt." },
  { es: "el archivo", de: "die Datei", pos: "noun", level: "B1", topic: "Technologie", ex: "No encuentro el archivo.", exDe: "Ich finde die Datei nicht." },
  { es: "la aplicación", de: "die App|die Anwendung", pos: "noun", level: "A2", topic: "Technologie", ex: "Descargué una nueva aplicación.", exDe: "Ich habe eine neue App heruntergeladen." },
  { es: "la red social", de: "das soziale Netzwerk", pos: "noun", level: "B1", topic: "Technologie", ex: "Pasa mucho tiempo en las redes sociales.", exDe: "Er verbringt viel Zeit in sozialen Netzwerken." },
  { es: "la cámara", de: "die Kamera", pos: "noun", level: "A2", topic: "Technologie", ex: "Compró una cámara nueva para el viaje.", exDe: "Er kaufte eine neue Kamera für die Reise." },
  { es: "la impresora", de: "der Drucker", pos: "noun", level: "B1", topic: "Technologie", ex: "La impresora se ha quedado sin tinta.", exDe: "Dem Drucker ist die Tinte ausgegangen." },
  { es: "descargar", de: "herunterladen", pos: "verb", level: "A2", topic: "Technologie", ex: "Voy a descargar el documento.", exDe: "Ich werde das Dokument herunterladen." },
  { es: "guardar", de: "speichern", pos: "verb", level: "A2", topic: "Technologie", ex: "Guarda los cambios antes de salir.", exDe: "Speichere die Änderungen, bevor du schließt." },
  { es: "buscar en internet", de: "im Internet suchen", pos: "phrase", level: "A2", topic: "Technologie", ex: "Voy a buscarlo en internet.", exDe: "Ich werde das im Internet suchen." },
  { es: "grabar", de: "aufnehmen", pos: "verb", level: "B1", topic: "Technologie", ex: "Grabé la reunión para no olvidarme.", exDe: "Ich habe die Besprechung aufgenommen, um nichts zu vergessen." },

  // --- Einkaufen & Geld ---
  { es: "el dinero", de: "das Geld", pos: "noun", level: "A1", topic: "Geld", ex: "No tengo dinero suelto.", exDe: "Ich habe kein Kleingeld." },
  { es: "el precio", de: "der Preis", pos: "noun", level: "A2", topic: "Geld", ex: "El precio ha subido mucho.", exDe: "Der Preis ist stark gestiegen." },
  { es: "el descuento", de: "der Rabatt", pos: "noun", level: "A2", topic: "Geld", ex: "Hay un veinte por ciento de descuento.", exDe: "Es gibt zwanzig Prozent Rabatt." },
  { es: "la tarjeta", de: "die Karte (Kredit-/Bankkarte)", pos: "noun", level: "A2", topic: "Geld", ex: "Pago con tarjeta, por favor.", exDe: "Ich zahle mit Karte, bitte." },
  { es: "el banco", de: "die Bank", pos: "noun", level: "A2", topic: "Geld", ex: "Abrí una cuenta en el banco.", exDe: "Ich habe ein Konto bei der Bank eröffnet." },
  { es: "la cuenta bancaria", de: "das Bankkonto", pos: "noun", level: "B1", topic: "Geld", ex: "Transferí el dinero a mi cuenta bancaria.", exDe: "Ich habe das Geld auf mein Bankkonto überwiesen." },
  { es: "gratis", de: "kostenlos", pos: "adj", level: "A2", topic: "Geld", ex: "La entrada es gratis los domingos.", exDe: "Der Eintritt ist sonntags kostenlos." },
  { es: "gastar", de: "ausgeben", pos: "verb", level: "A2", topic: "Geld", ex: "Gasté demasiado este mes.", exDe: "Ich habe diesen Monat zu viel ausgegeben." },
  { es: "ahorrar", de: "sparen", pos: "verb", level: "A2", topic: "Geld", ex: "Intento ahorrar cada mes.", exDe: "Ich versuche, jeden Monat zu sparen." },
  { es: "vender", de: "verkaufen", pos: "verb", level: "A2", topic: "Geld", ex: "Vendió su coche viejo.", exDe: "Er hat sein altes Auto verkauft." },
  { es: "costar", de: "kosten", pos: "verb", level: "A1", topic: "Geld", ex: "¿Cuánto cuesta esta camisa?", exDe: "Wie viel kostet dieses Hemd?" },
  { es: "el supermercado", de: "der Supermarkt", pos: "noun", level: "A1", topic: "Einkaufen", ex: "Voy al supermercado a comprar leche.", exDe: "Ich gehe zum Supermarkt, um Milch zu kaufen." },
  { es: "el mercado", de: "der Markt", pos: "noun", level: "A2", topic: "Einkaufen", ex: "Compro verdura fresca en el mercado.", exDe: "Ich kaufe frisches Gemüse auf dem Markt." },
  { es: "el centro comercial", de: "das Einkaufszentrum", pos: "noun", level: "A2", topic: "Einkaufen", ex: "El centro comercial está lleno los sábados.", exDe: "Das Einkaufszentrum ist samstags voll." },
  { es: "la talla", de: "die Größe (Kleidung)", pos: "noun", level: "B1", topic: "Einkaufen", ex: "¿Qué talla usas?", exDe: "Welche Größe trägst du?" },
  { es: "probarse", de: "anprobieren", pos: "verb", level: "B1", topic: "Einkaufen", ex: "Quiero probarme estos pantalones.", exDe: "Ich möchte diese Hose anprobieren." },

  // --- Sport & Freizeit ---
  { es: "el deporte", de: "der Sport", pos: "noun", level: "A1", topic: "Sport", ex: "Hago deporte tres veces por semana.", exDe: "Ich mache dreimal die Woche Sport." },
  { es: "el fútbol", de: "der Fußball", pos: "noun", level: "A1", topic: "Sport", ex: "Jugamos al fútbol los domingos.", exDe: "Wir spielen sonntags Fußball." },
  { es: "nadar", de: "schwimmen", pos: "verb", level: "A1", topic: "Sport", ex: "Nado en la piscina todos los días.", exDe: "Ich schwimme jeden Tag im Schwimmbad." },
  { es: "el equipo", de: "das Team|die Mannschaft", pos: "noun", level: "A2", topic: "Sport", ex: "Nuestro equipo ganó el partido.", exDe: "Unsere Mannschaft hat das Spiel gewonnen." },
  { es: "el partido", de: "das Spiel (Sport)", pos: "noun", level: "A2", topic: "Sport", ex: "El partido empieza a las ocho.", exDe: "Das Spiel beginnt um acht." },
  { es: "entrenar", de: "trainieren", pos: "verb", level: "A2", topic: "Sport", ex: "Entrena todos los días después del trabajo.", exDe: "Er trainiert jeden Tag nach der Arbeit." },
  { es: "el gimnasio", de: "das Fitnessstudio", pos: "noun", level: "A2", topic: "Sport", ex: "Voy al gimnasio por la mañana.", exDe: "Ich gehe morgens ins Fitnessstudio." },
  { es: "la bicicleta", de: "das Fahrrad", pos: "noun", level: "A1", topic: "Sport", ex: "Voy al trabajo en bicicleta.", exDe: "Ich fahre mit dem Fahrrad zur Arbeit." },
  { es: "el tiempo libre", de: "die Freizeit", pos: "noun", level: "A2", topic: "Freizeit", ex: "En mi tiempo libre leo mucho.", exDe: "In meiner Freizeit lese ich viel." },
  { es: "la película", de: "der Film", pos: "noun", level: "A1", topic: "Freizeit", ex: "Vimos una película muy buena.", exDe: "Wir haben einen sehr guten Film gesehen." },
  { es: "la música", de: "die Musik", pos: "noun", level: "A1", topic: "Freizeit", ex: "Escucho música mientras trabajo.", exDe: "Ich höre Musik, während ich arbeite." },
  { es: "el libro", de: "das Buch", pos: "noun", level: "A1", topic: "Freizeit", ex: "Estoy leyendo un libro interesante.", exDe: "Ich lese gerade ein interessantes Buch." },
  { es: "la fiesta", de: "die Party|das Fest", pos: "noun", level: "A1", topic: "Freizeit", ex: "La fiesta duró hasta las tres.", exDe: "Die Party dauerte bis drei Uhr." },
  { es: "el juego", de: "das Spiel", pos: "noun", level: "A2", topic: "Freizeit", ex: "Los niños inventaron un juego nuevo.", exDe: "Die Kinder haben sich ein neues Spiel ausgedacht." },
  { es: "pintar", de: "malen", pos: "verb", level: "A2", topic: "Freizeit", ex: "Le gusta pintar paisajes.", exDe: "Er malt gerne Landschaften." },
  { es: "dibujar", de: "zeichnen", pos: "verb", level: "A2", topic: "Freizeit", ex: "Dibuja muy bien.", exDe: "Sie zeichnet sehr gut." },
  { es: "descansar en el sofá", de: "sich auf dem Sofa entspannen", pos: "phrase", level: "A2", topic: "Freizeit", ex: "Los domingos descanso en el sofá.", exDe: "Sonntags entspanne ich mich auf dem Sofa." },

  // --- Adjektive erweitert ---
  { es: "alto", de: "groß|hoch (Person)", pos: "adj", level: "A1", topic: "Adjektive", ex: "Es el jugador más alto del equipo.", exDe: "Er ist der größte Spieler im Team." },
  { es: "joven", de: "jung", pos: "adj", level: "A1", topic: "Adjektive", ex: "El nuevo jefe es muy joven.", exDe: "Der neue Chef ist sehr jung." },
  { es: "guapo", de: "hübsch|gutaussehend", pos: "adj", level: "A2", topic: "Adjektive", ex: "Su hermano es muy guapo.", exDe: "Ihr Bruder ist sehr gutaussehend." },
  { es: "feo", de: "hässlich", pos: "adj", level: "A2", topic: "Adjektive", ex: "Ese edificio es bastante feo.", exDe: "Dieses Gebäude ist ziemlich hässlich." },
  { es: "delgado", de: "schlank|dünn", pos: "adj", level: "A2", topic: "Adjektive", ex: "Está más delgado que antes.", exDe: "Er ist schlanker als früher." },
  { es: "gordo", de: "dick", pos: "adj", level: "A2", topic: "Adjektive", ex: "El perro está un poco gordo.", exDe: "Der Hund ist etwas dick." },
  { es: "fuerte", de: "stark|kräftig", pos: "adj", level: "A2", topic: "Adjektive", ex: "Hace falta ser fuerte para este trabajo.", exDe: "Für diese Arbeit muss man stark sein." },
  { es: "débil", de: "schwach", pos: "adj", level: "B1", topic: "Adjektive", ex: "Se sentía muy débil después de la gripe.", exDe: "Er fühlte sich nach der Grippe sehr schwach." },
  { es: "rápido", de: "schnell", pos: "adj", level: "A1", topic: "Adjektive", ex: "Es un coche muy rápido.", exDe: "Es ist ein sehr schnelles Auto." },
  { es: "lento", de: "langsam", pos: "adj", level: "A2", topic: "Adjektive", ex: "El tren es muy lento hoy.", exDe: "Der Zug ist heute sehr langsam." },
  { es: "limpio", de: "sauber", pos: "adj", level: "A2", topic: "Adjektive", ex: "La cocina está muy limpia.", exDe: "Die Küche ist sehr sauber." },
  { es: "sucio", de: "schmutzig", pos: "adj", level: "A2", topic: "Adjektive", ex: "Tienes las manos sucias.", exDe: "Deine Hände sind schmutzig." },
  { es: "lleno", de: "voll", pos: "adj", level: "A2", topic: "Adjektive", ex: "El autobús estaba completamente lleno.", exDe: "Der Bus war völlig voll." },
  { es: "vacío", de: "leer", pos: "adj", level: "A2", topic: "Adjektive", ex: "La botella está vacía.", exDe: "Die Flasche ist leer." },
  { es: "abierto", de: "offen|geöffnet", pos: "adj", level: "A2", topic: "Adjektive", ex: "La tienda está abierta hasta las ocho.", exDe: "Der Laden ist bis acht geöffnet." },
  { es: "cerrado", de: "geschlossen", pos: "adj", level: "A2", topic: "Adjektive", ex: "El museo está cerrado los lunes.", exDe: "Das Museum ist montags geschlossen." },
  { es: "seguro", de: "sicher", pos: "adj", level: "A2", topic: "Adjektive", ex: "No estoy seguro de la respuesta.", exDe: "Ich bin mir bei der Antwort nicht sicher." },
  { es: "peligroso", de: "gefährlich", pos: "adj", level: "B1", topic: "Adjektive", ex: "Nadar aquí es peligroso.", exDe: "Hier zu schwimmen ist gefährlich." },
  { es: "libre", de: "frei", pos: "adj", level: "A2", topic: "Adjektive", ex: "¿Está libre esta silla?", exDe: "Ist dieser Stuhl frei?" },
  { es: "importante", de: "wichtig", pos: "adj", level: "A1", topic: "Adjektive", ex: "Es muy importante llegar a tiempo.", exDe: "Es ist sehr wichtig, pünktlich zu sein." },
  { es: "interesante", de: "interessant", pos: "adj", level: "A1", topic: "Adjektive", ex: "El curso es muy interesante.", exDe: "Der Kurs ist sehr interessant." },
  { es: "aburrido", de: "langweilig", pos: "adj", level: "A2", topic: "Adjektive", ex: "La reunión fue bastante aburrida.", exDe: "Die Besprechung war ziemlich langweilig." },
  { es: "divertido", de: "lustig|unterhaltsam", pos: "adj", level: "A2", topic: "Adjektive", ex: "Fue un fin de semana muy divertido.", exDe: "Es war ein sehr unterhaltsames Wochenende." },
  { es: "triste", de: "traurig", pos: "adj", level: "A2", topic: "Adjektive", ex: "Está triste porque perdió el partido.", exDe: "Er ist traurig, weil er das Spiel verloren hat." },
  { es: "feliz", de: "glücklich", pos: "adj", level: "A1", topic: "Adjektive", ex: "Se ve muy feliz últimamente.", exDe: "Er sieht in letzter Zeit sehr glücklich aus." },
  { es: "enfadado", de: "wütend|verärgert", pos: "adj", level: "A2", topic: "Adjektive", ex: "Está enfadado conmigo.", exDe: "Er ist wütend auf mich." },
  { es: "nervioso", de: "nervös", pos: "adj", level: "A2", topic: "Adjektive", ex: "Está nerviosa por el examen.", exDe: "Sie ist wegen der Prüfung nervös." },
  { es: "tranquilo", de: "ruhig", pos: "adj", level: "A2", topic: "Adjektive", ex: "Es un barrio muy tranquilo.", exDe: "Es ist ein sehr ruhiges Viertel." },
  { es: "sorprendido", de: "überrascht", pos: "adj", level: "B1", topic: "Adjektive", ex: "Me quedé sorprendido con la noticia.", exDe: "Ich war überrascht von der Nachricht." },
  { es: "orgulloso", de: "stolz", pos: "adj", level: "B1", topic: "Adjektive", ex: "Está muy orgulloso de su hija.", exDe: "Er ist sehr stolz auf seine Tochter." },
  { es: "generoso", de: "großzügig", pos: "adj", level: "B1", topic: "Adjektive", ex: "Es una persona muy generosa.", exDe: "Er ist ein sehr großzügiger Mensch." },
  { es: "honesto", de: "ehrlich", pos: "adj", level: "B1", topic: "Adjektive", ex: "Siempre es honesto conmigo.", exDe: "Er ist immer ehrlich zu mir." },
  { es: "perezoso", de: "faul", pos: "adj", level: "B1", topic: "Adjektive", ex: "Es un poco perezoso por las mañanas.", exDe: "Er ist morgens etwas faul." },
  { es: "inteligente", de: "intelligent|klug", pos: "adj", level: "A2", topic: "Adjektive", ex: "Es una estudiante muy inteligente.", exDe: "Sie ist eine sehr kluge Studentin." },
  { es: "simpático", de: "sympathisch|nett", pos: "adj", level: "A2", topic: "Adjektive", ex: "Todos mis compañeros son muy simpáticos.", exDe: "Alle meine Kollegen sind sehr nett." },
  { es: "tímido", de: "schüchtern", pos: "adj", level: "B1", topic: "Adjektive", ex: "De niño era muy tímido.", exDe: "Als Kind war er sehr schüchtern." },
  { es: "curioso", de: "neugierig", pos: "adj", level: "B1", topic: "Adjektive", ex: "Los niños son muy curiosos.", exDe: "Kinder sind sehr neugierig." },
  { es: "posible", de: "möglich", pos: "adj", level: "A2", topic: "Adjektive", ex: "Es posible que llueva mañana.", exDe: "Es ist möglich, dass es morgen regnet." },
  { es: "cierto", de: "sicher|gewiss|richtig", pos: "adj", level: "B1", topic: "Adjektive", ex: "No estoy cierto de eso.", exDe: "Ich bin mir da nicht sicher." },
  { es: "correcto", de: "richtig|korrekt", pos: "adj", level: "A2", topic: "Adjektive", ex: "Tu respuesta es correcta.", exDe: "Deine Antwort ist richtig." },
  { es: "diferente", de: "anders|unterschiedlich", pos: "adj", level: "A2", topic: "Adjektive", ex: "Cada país es diferente.", exDe: "Jedes Land ist anders." },
  { es: "igual", de: "gleich", pos: "adj", level: "A2", topic: "Adjektive", ex: "Los dos vestidos son casi iguales.", exDe: "Die beiden Kleider sind fast gleich." },
  { es: "propio", de: "eigen", pos: "adj", level: "B1", topic: "Adjektive", ex: "Tiene su propio negocio.", exDe: "Er hat sein eigenes Geschäft." },

  // --- Adverbien & Quantoren ---
  { es: "muy", de: "sehr", pos: "adv", level: "A1", topic: "Adverbien", ex: "Estoy muy cansado.", exDe: "Ich bin sehr müde." },
  { es: "mucho", de: "viel", pos: "adv", level: "A1", topic: "Adverbien", ex: "Trabaja mucho estos días.", exDe: "Er arbeitet dieser Tage viel." },
  { es: "poco", de: "wenig", pos: "adv", level: "A1", topic: "Adverbien", ex: "Duerme muy poco.", exDe: "Er schläft sehr wenig." },
  { es: "bastante", de: "ziemlich|genug", pos: "adv", level: "A2", topic: "Adverbien", ex: "Es bastante difícil.", exDe: "Es ist ziemlich schwierig." },
  { es: "demasiado", de: "zu viel|zu sehr", pos: "adv", level: "A2", topic: "Adverbien", ex: "Comiste demasiado.", exDe: "Du hast zu viel gegessen." },
  { es: "casi", de: "fast", pos: "adv", level: "A2", topic: "Adverbien", ex: "Ya casi hemos terminado.", exDe: "Wir sind fast fertig." },
  { es: "solo", de: "nur|allein", pos: "adv", level: "A1", topic: "Adverbien", ex: "Solo quiero descansar.", exDe: "Ich möchte nur ausruhen." },
  { es: "también", de: "auch", pos: "adv", level: "A1", topic: "Adverbien", ex: "Yo también quiero ir.", exDe: "Ich möchte auch gehen." },
  { es: "tampoco", de: "auch nicht", pos: "adv", level: "A2", topic: "Adverbien", ex: "Yo tampoco lo sabía.", exDe: "Ich wusste es auch nicht." },
  { es: "aquí", de: "hier", pos: "adv", level: "A1", topic: "Adverbien", ex: "Vivo aquí desde hace un año.", exDe: "Ich wohne seit einem Jahr hier." },
  { es: "allí", de: "dort", pos: "adv", level: "A1", topic: "Adverbien", ex: "El libro está allí, en la estantería.", exDe: "Das Buch ist dort im Regal." },
  { es: "cerca", de: "nah|in der Nähe", pos: "adv", level: "A1", topic: "Adverbien", ex: "El colegio está cerca de casa.", exDe: "Die Schule ist in der Nähe des Hauses." },
  { es: "lejos", de: "weit|weit weg", pos: "adv", level: "A1", topic: "Adverbien", ex: "El aeropuerto está lejos del centro.", exDe: "Der Flughafen ist weit vom Zentrum entfernt." },
  { es: "dentro", de: "innen|drinnen", pos: "adv", level: "A2", topic: "Adverbien", ex: "Prefiero comer dentro.", exDe: "Ich esse lieber drinnen." },
  { es: "fuera", de: "draußen", pos: "adv", level: "A2", topic: "Adverbien", ex: "Los niños juegan fuera.", exDe: "Die Kinder spielen draußen." },
  { es: "arriba", de: "oben", pos: "adv", level: "A2", topic: "Adverbien", ex: "El dormitorio está arriba.", exDe: "Das Schlafzimmer ist oben." },
  { es: "abajo", de: "unten", pos: "adv", level: "A2", topic: "Adverbien", ex: "La cocina está abajo.", exDe: "Die Küche ist unten." },
  { es: "despacio", de: "langsam", pos: "adv", level: "A2", topic: "Adverbien", ex: "Habla más despacio, por favor.", exDe: "Sprich bitte langsamer." },
  { es: "juntos", de: "zusammen", pos: "adv", level: "A2", topic: "Adverbien", ex: "Fuimos juntos al concierto.", exDe: "Wir sind zusammen zum Konzert gegangen." },
  { es: "solamente", de: "nur|ausschließlich", pos: "adv", level: "B1", topic: "Adverbien", ex: "Solamente falta una firma.", exDe: "Es fehlt nur noch eine Unterschrift." },
  { es: "realmente", de: "wirklich", pos: "adv", level: "B1", topic: "Adverbien", ex: "No sé realmente qué hacer.", exDe: "Ich weiß wirklich nicht, was ich tun soll." },
  { es: "totalmente", de: "völlig|total", pos: "adv", level: "B1", topic: "Adverbien", ex: "Estoy totalmente de acuerdo.", exDe: "Ich stimme völlig zu." },
  { es: "especialmente", de: "besonders", pos: "adv", level: "B1", topic: "Adverbien", ex: "Me gusta especialmente el otoño.", exDe: "Ich mag besonders den Herbst." },
  { es: "normalmente", de: "normalerweise", pos: "adv", level: "A2", topic: "Adverbien", ex: "Normalmente ceno a las nueve.", exDe: "Normalerweise esse ich um neun zu Abend." },

  // --- Stadt & Haus erweitert ---
  { es: "el barrio", de: "das Viertel", pos: "noun", level: "A2", topic: "Stadt", ex: "Vivimos en un barrio tranquilo.", exDe: "Wir wohnen in einem ruhigen Viertel." },
  { es: "el edificio", de: "das Gebäude", pos: "noun", level: "A2", topic: "Stadt", ex: "Ese edificio es del siglo pasado.", exDe: "Dieses Gebäude ist aus dem letzten Jahrhundert." },
  { es: "el parque", de: "der Park", pos: "noun", level: "A1", topic: "Stadt", ex: "Paseamos por el parque los domingos.", exDe: "Sonntags spazieren wir durch den Park." },
  { es: "la plaza", de: "der Platz", pos: "noun", level: "A2", topic: "Stadt", ex: "Nos vemos en la plaza mayor.", exDe: "Wir treffen uns auf dem Hauptplatz." },
  { es: "el semáforo", de: "die Ampel", pos: "noun", level: "B1", topic: "Stadt", ex: "Cruza cuando el semáforo esté en verde.", exDe: "Überquere, wenn die Ampel grün ist." },
  { es: "la acera", de: "der Gehweg|der Bürgersteig", pos: "noun", level: "B1", topic: "Stadt", ex: "Camina por la acera, no por la calle.", exDe: "Geh auf dem Gehweg, nicht auf der Straße." },
  { es: "el ayuntamiento", de: "das Rathaus", pos: "noun", level: "B1", topic: "Stadt", ex: "El ayuntamiento está en el centro.", exDe: "Das Rathaus liegt im Zentrum." },
  { es: "la iglesia", de: "die Kirche", pos: "noun", level: "A2", topic: "Stadt", ex: "La iglesia está al lado del parque.", exDe: "Die Kirche steht neben dem Park." },
  { es: "el museo", de: "das Museum", pos: "noun", level: "A2", topic: "Stadt", ex: "Visitamos un museo de arte moderno.", exDe: "Wir haben ein Museum für moderne Kunst besucht." },
  { es: "el hotel", de: "das Hotel", pos: "noun", level: "A1", topic: "Reisen", ex: "Reservamos un hotel cerca de la playa.", exDe: "Wir haben ein Hotel in Strandnähe gebucht." },
  { es: "la estación", de: "der Bahnhof|die Station", pos: "noun", level: "A2", topic: "Reisen", ex: "La estación está a diez minutos a pie.", exDe: "Der Bahnhof ist zehn Minuten zu Fuß entfernt." },
  { es: "el aeropuerto", de: "der Flughafen", pos: "noun", level: "A2", topic: "Reisen", ex: "Llegamos al aeropuerto con tiempo.", exDe: "Wir kamen rechtzeitig am Flughafen an." },
  { es: "el pasaporte", de: "der Reisepass", pos: "noun", level: "A2", topic: "Reisen", ex: "No olvides el pasaporte.", exDe: "Vergiss den Reisepass nicht." },
  { es: "la maleta", de: "der Koffer", pos: "noun", level: "A2", topic: "Reisen", ex: "Todavía no he hecho la maleta.", exDe: "Ich habe den Koffer noch nicht gepackt." },
  { es: "el mapa", de: "die Karte (Landkarte)", pos: "noun", level: "A2", topic: "Reisen", ex: "Miramos el mapa antes de salir.", exDe: "Wir haben vor der Abfahrt auf die Karte geschaut." },
  { es: "el sofá", de: "das Sofa", pos: "noun", level: "A2", topic: "Zuhause", ex: "Me quedé dormido en el sofá.", exDe: "Ich bin auf dem Sofa eingeschlafen." },
  { es: "el armario", de: "der Schrank", pos: "noun", level: "A2", topic: "Zuhause", ex: "Guarda la ropa en el armario.", exDe: "Räum die Kleidung in den Schrank." },
  { es: "el espejo", de: "der Spiegel", pos: "noun", level: "B1", topic: "Zuhause", ex: "Se miró en el espejo antes de salir.", exDe: "Er schaute vor dem Rausgehen in den Spiegel." },
  { es: "la lámpara", de: "die Lampe", pos: "noun", level: "A2", topic: "Zuhause", ex: "Enciende la lámpara, está oscuro.", exDe: "Schalte die Lampe an, es ist dunkel." },
  { es: "el jardín", de: "der Garten", pos: "noun", level: "A2", topic: "Zuhause", ex: "Los niños juegan en el jardín.", exDe: "Die Kinder spielen im Garten." },
  { es: "el baño", de: "das Badezimmer", pos: "noun", level: "A1", topic: "Zuhause", ex: "El baño está al final del pasillo.", exDe: "Das Badezimmer ist am Ende des Flurs." },
  { es: "la pared", de: "die Wand", pos: "noun", level: "A2", topic: "Zuhause", ex: "Colgamos un cuadro en la pared.", exDe: "Wir haben ein Bild an die Wand gehängt." },
  { es: "el suelo", de: "der Boden", pos: "noun", level: "A2", topic: "Zuhause", ex: "Se cayó al suelo.", exDe: "Er ist zu Boden gefallen." },
  { es: "el piso", de: "die Wohnung|das Stockwerk", pos: "noun", level: "A2", topic: "Zuhause", ex: "Alquilamos un piso en el centro.", exDe: "Wir haben eine Wohnung im Zentrum gemietet." },
  { es: "alquilar", de: "mieten|vermieten", pos: "verb", level: "A2", topic: "Zuhause", ex: "Vamos a alquilar un coche.", exDe: "Wir werden ein Auto mieten." },
  { es: "mudarse", de: "umziehen", pos: "verb", level: "B1", topic: "Zuhause", ex: "Nos mudamos el mes que viene.", exDe: "Wir ziehen nächsten Monat um." },

  // --- Redemittel & Konnektoren erweitert ---
  { es: "claro", de: "klar|natürlich", pos: "phrase", level: "A2", topic: "Redemittel", ex: "—¿Vienes? —¡Claro!", exDe: "„Kommst du?“ – „Klar!“" },
  { es: "de acuerdo", de: "einverstanden", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Estoy de acuerdo contigo.", exDe: "Ich bin mit dir einverstanden." },
  { es: "en realidad", de: "eigentlich|tatsächlich", pos: "phrase", level: "B1", topic: "Redemittel", ex: "En realidad no me gusta.", exDe: "Eigentlich gefällt mir das nicht." },
  { es: "es decir", de: "das heißt", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Llega mañana, es decir, el martes.", exDe: "Er kommt morgen, das heißt, am Dienstag." },
  { es: "por ejemplo", de: "zum Beispiel", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Podríamos ir, por ejemplo, al cine.", exDe: "Wir könnten zum Beispiel ins Kino gehen." },
  { es: "por lo menos", de: "wenigstens|zumindest", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Al menos llegamos a tiempo.", exDe: "Wenigstens sind wir pünktlich angekommen." },
  { es: "de todos modos", de: "sowieso|auf jeden Fall", pos: "phrase", level: "B1", topic: "Redemittel", ex: "De todos modos, gracias por venir.", exDe: "Danke, dass du trotzdem gekommen bist." },
  { es: "a veces", de: "manchmal", pos: "phrase", level: "A1", topic: "Redemittel", ex: "A veces trabajo desde casa.", exDe: "Manchmal arbeite ich von zu Hause." },
  { es: "de nuevo", de: "wieder|erneut", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Inténtalo de nuevo.", exDe: "Versuch es noch einmal." },
  { es: "cuanto antes", de: "so schnell wie möglich", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Llámame cuanto antes.", exDe: "Ruf mich so schnell wie möglich an." },
  { es: "no pasa nada", de: "das macht nichts|kein Problem", pos: "phrase", level: "A2", topic: "Redemittel", ex: "—Lo siento. —No pasa nada.", exDe: "„Es tut mir leid.“ – „Kein Problem.“" },
  { es: "no importa", de: "es macht nichts|egal", pos: "phrase", level: "A2", topic: "Redemittel", ex: "No importa, lo haremos mañana.", exDe: "Egal, wir machen es morgen." },
  { es: "hacer falta", de: "nötig sein|fehlen", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Hace falta más tiempo.", exDe: "Es braucht mehr Zeit." },
  { es: "tener razón", de: "recht haben", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Creo que tienes razón.", exDe: "Ich glaube, du hast recht." },
  { es: "tener prisa", de: "es eilig haben", pos: "phrase", level: "A2", topic: "Redemittel", ex: "No puedo hablar ahora, tengo prisa.", exDe: "Ich kann jetzt nicht reden, ich hab's eilig." },
  { es: "tener suerte", de: "Glück haben", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Tuvimos mucha suerte con el tiempo.", exDe: "Wir hatten viel Glück mit dem Wetter." },
  { es: "tener sueño", de: "müde sein", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Tengo mucho sueño hoy.", exDe: "Ich bin heute sehr müde." },
  { es: "tener miedo", de: "Angst haben", pos: "phrase", level: "A2", topic: "Redemittel", ex: "Tiene miedo a las alturas.", exDe: "Er hat Höhenangst." },
  { es: "hacer caso", de: "beachten|zuhören", pos: "phrase", level: "B1", topic: "Redemittel", ex: "Nadie me hace caso.", exDe: "Niemand hört mir zu." },
  { es: "ponerse de acuerdo", de: "sich einigen", pos: "phrase", level: "B1", topic: "Redemittel", ex: "No conseguimos ponernos de acuerdo.", exDe: "Wir konnten uns nicht einigen." },
];
