/* Grammar drills: closed questions (gap text with multiple choice), so
   everything stays unambiguously gradable without an AI judging it. */
const GRAMMAR = (() => {
  const CATEGORY_LABELS = {
    ser_estar: "Ser vs. estar",
    por_para: "Por vs. para",
    articles: "Artikel & Genus",
    prepositions: "Verb + Präposition",
  };
  const CATEGORY_EXPLANATIONS = {
    ser_estar: "„Ser“ für Identität, Herkunft, Beruf und dauerhafte Eigenschaften. „Estar“ für Ort, Zustand und Ergebnis einer Veränderung.",
    por_para: "„Para“ für Zweck, Ziel, Empfänger und Frist. „Por“ für Grund, Ursache, Tausch, Dauer und „durch“.",
    articles: "Viele spanische Nomen haben ein Genus, das man dem Wortende nicht ansieht — am besten direkt mit Artikel lernen.",
    prepositions: "Viele spanische Verben verlangen feste Präpositionen, die oft nicht der deutschen Entsprechung folgen.",
  };

  const ITEMS = [
    // --- ser vs. estar ---
    { id: "se1", category: "ser_estar", prompt: "Yo ___ profesor.", options: ["soy", "estoy"], answer: "soy",
      explanation: "Beruf = dauerhafte Eigenschaft → ser." },
    { id: "se2", category: "ser_estar", prompt: "Madrid ___ en España.", options: ["es", "está"], answer: "está",
      explanation: "Lage einer Stadt/eines Ortes → estar." },
    { id: "se3", category: "ser_estar", prompt: "Ella ___ muy inteligente.", options: ["es", "está"], answer: "es",
      explanation: "Charaktereigenschaft → ser." },
    { id: "se4", category: "ser_estar", prompt: "Hoy ___ cansado.", options: ["soy", "estoy"], answer: "estoy",
      explanation: "Vorübergehender Zustand (heute) → estar." },
    { id: "se5", category: "ser_estar", prompt: "¿Cómo ___ tu madre? (Ich möchte wissen, wie sie als Person ist.)", options: ["es", "está"], answer: "es",
      explanation: "Frage nach der Persönlichkeit/dem Wesen → ser." },
    { id: "se6", category: "ser_estar", prompt: "¿Cómo ___ tu madre? (Ich möchte wissen, ob es ihr gesundheitlich gut geht.)", options: ["es", "está"], answer: "está",
      explanation: "Frage nach dem aktuellen Befinden → estar." },
    { id: "se7", category: "ser_estar", prompt: "La puerta ___ abierta.", options: ["es", "está"], answer: "está",
      explanation: "Ergebnis einer Handlung/Zustand → estar." },
    { id: "se8", category: "ser_estar", prompt: "El concierto ___ en el estadio.", options: ["es", "está"], answer: "es",
      explanation: "Ausnahme: Der Ort einer Veranstaltung (wo etwas stattfindet) nutzt ser, nicht estar." },
    { id: "se9", category: "ser_estar", prompt: "Nosotros ___ de Alemania.", options: ["somos", "estamos"], answer: "somos",
      explanation: "Herkunft → ser." },
    { id: "se10", category: "ser_estar", prompt: "Juan ___ aburrido. No tiene nada que hacer.", options: ["es", "está"], answer: "está",
      explanation: "„Estar aburrido“ = sich langweilen (Zustand). „Ser aburrido“ würde heißen, er ist eine langweilige Person." },
    { id: "se11", category: "ser_estar", prompt: "Esta película ___ muy aburrida.", options: ["es", "está"], answer: "es",
      explanation: "„Ser aburrido“ hier: Eigenschaft des Films (er ist langweilig)." },
    { id: "se12", category: "ser_estar", prompt: "___ las tres de la tarde.", options: ["Son", "Están"], answer: "Son",
      explanation: "Uhrzeiten werden immer mit ser gebildet." },
    { id: "se13", category: "ser_estar", prompt: "La comida ya ___ lista.", options: ["es", "está"], answer: "está",
      explanation: "„Listo“ mit estar = fertig/bereit (Zustand)." },
    { id: "se14", category: "ser_estar", prompt: "Él ___ médico.", options: ["es", "está"], answer: "es",
      explanation: "Beruf → ser." },
    { id: "se15", category: "ser_estar", prompt: "Yo ___ muy contento con los resultados.", options: ["soy", "estoy"], answer: "estoy",
      explanation: "Emotionaler, vorübergehender Zustand → estar." },

    // --- por vs. para ---
    { id: "pp1", category: "por_para", prompt: "Este regalo es ___ ti.", options: ["por", "para"], answer: "para",
      explanation: "Empfänger einer Handlung → para." },
    { id: "pp2", category: "por_para", prompt: "Trabajo ___ ganar dinero.", options: ["por", "para"], answer: "para",
      explanation: "Zweck/Ziel einer Handlung → para." },
    { id: "pp3", category: "por_para", prompt: "Gracias ___ tu ayuda.", options: ["por", "para"], answer: "por",
      explanation: "Grund/Ursache → por." },
    { id: "pp4", category: "por_para", prompt: "Pasamos ___ el parque de camino a casa.", options: ["por", "para"], answer: "por",
      explanation: "Bewegung „durch“ einen Ort → por." },
    { id: "pp5", category: "por_para", prompt: "Necesito el informe ___ el lunes.", options: ["por", "para"], answer: "para",
      explanation: "Frist/Deadline → para." },
    { id: "pp6", category: "por_para", prompt: "Cambié mi coche viejo ___ uno nuevo.", options: ["por", "para"], answer: "por",
      explanation: "Tausch/Austausch → por." },
    { id: "pp7", category: "por_para", prompt: "Estudio español ___ viajar a España.", options: ["por", "para"], answer: "para",
      explanation: "Zweck/Ziel → para." },
    { id: "pp8", category: "por_para", prompt: "Te llamo ___ preguntarte algo.", options: ["por", "para"], answer: "para",
      explanation: "Zweck des Anrufs → para." },
    { id: "pp9", category: "por_para", prompt: "Caminamos ___ la playa durante una hora.", options: ["por", "para"], answer: "por",
      explanation: "„Entlang/durch“ einen Bereich, unbestimmte Bewegung → por." },
    { id: "pp10", category: "por_para", prompt: "El tren sale ___ Madrid.", options: ["por", "para"], answer: "para",
      explanation: "Reiseziel/Richtung → para." },
    { id: "pp11", category: "por_para", prompt: "___ mí, esta es la mejor opción.", options: ["Por", "Para"], answer: "Para",
      explanation: "„Para mí“ = meiner Meinung nach — feste Wendung mit para." },
    { id: "pp12", category: "por_para", prompt: "Multan a los conductores ___ exceso de velocidad.", options: ["por", "para"], answer: "por",
      explanation: "Grund einer Strafe/Handlung → por." },
    { id: "pp13", category: "por_para", prompt: "Compré flores ___ mi madre.", options: ["por", "para"], answer: "para",
      explanation: "Empfänger → para." },
    { id: "pp14", category: "por_para", prompt: "Ella trabaja ___ la mañana.", options: ["por", "para"], answer: "por",
      explanation: "Tageszeitangaben (por la mañana/tarde/noche) nutzen immer por." },
    { id: "pp15", category: "por_para", prompt: "Pagué veinte euros ___ el libro.", options: ["por", "para"], answer: "por",
      explanation: "Preis/Gegenwert → por." },

    // --- articles & gender ---
    { id: "ar1", category: "articles", prompt: "___ problema", options: ["el", "la"], answer: "el",
      explanation: "„Problema“ endet auf -a, ist aber männlich (griechischen Ursprungs, wie viele -ma-Wörter)." },
    { id: "ar2", category: "articles", prompt: "___ día", options: ["el", "la"], answer: "el",
      explanation: "„Día“ endet auf -a, ist aber männlich — eine der bekanntesten Ausnahmen." },
    { id: "ar3", category: "articles", prompt: "___ mano", options: ["el", "la"], answer: "la",
      explanation: "„Mano“ endet auf -o, ist aber weiblich — die bekannteste Gegenausnahme." },
    { id: "ar4", category: "articles", prompt: "___ mapa", options: ["el", "la"], answer: "el",
      explanation: "Ein weiteres -ma-Wort griechischen Ursprungs: männlich trotz -a." },
    { id: "ar5", category: "articles", prompt: "___ foto", options: ["el", "la"], answer: "la",
      explanation: "Kurzform von „fotografía“ — bleibt weiblich, obwohl es auf -o endet." },
    { id: "ar6", category: "articles", prompt: "___ agua fría", options: ["el", "la"], answer: "el",
      explanation: "„Agua“ ist grammatisch weiblich, nutzt aber „el“ wegen des betonten a-Lauts am Wortanfang. Adjektive bleiben trotzdem weiblich: „el agua fría“." },
    { id: "ar7", category: "articles", prompt: "___ sistema", options: ["el", "la"], answer: "el",
      explanation: "Noch ein männliches -ma-Wort: el sistema." },
    { id: "ar8", category: "articles", prompt: "___ radio (das Medium/der Sender)", options: ["el", "la"], answer: "la",
      explanation: "In Spanien weiblich für das Medium; in Teilen Lateinamerikas wird „el radio“ für das Gerät verwendet." },
    { id: "ar9", category: "articles", prompt: "___ idioma", options: ["el", "la"], answer: "el",
      explanation: "Männliches -ma-Wort: el idioma." },
    { id: "ar10", category: "articles", prompt: "___ clima", options: ["el", "la"], answer: "el",
      explanation: "Männliches -ma-Wort: el clima." },
    { id: "ar11", category: "articles", prompt: "___ moto", options: ["el", "la"], answer: "la",
      explanation: "Kurzform von „motocicleta“ — bleibt weiblich." },
    { id: "ar12", category: "articles", prompt: "___ planeta", options: ["el", "la"], answer: "el",
      explanation: "Männliches -ma-Wort: el planeta." },
    { id: "ar13", category: "articles", prompt: "___ crisis", options: ["el", "la"], answer: "la",
      explanation: "Wörter auf -is sind meist weiblich: la crisis." },

    // --- verb + preposition ---
    { id: "vp1", category: "prepositions", prompt: "pensar ___ algo", options: ["en", "de", "con"], answer: "en",
      explanation: "pensar en = an etwas denken." },
    { id: "vp2", category: "prepositions", prompt: "soñar ___ algo", options: ["en", "con", "de"], answer: "con",
      explanation: "soñar con = von etwas träumen." },
    { id: "vp3", category: "prepositions", prompt: "depender ___ algo", options: ["de", "en", "con"], answer: "de",
      explanation: "depender de = von etwas abhängen." },
    { id: "vp4", category: "prepositions", prompt: "consistir ___ algo", options: ["en", "de", "a"], answer: "en",
      explanation: "consistir en = in etwas bestehen." },
    { id: "vp5", category: "prepositions", prompt: "enamorarse ___ alguien", options: ["con", "de", "en"], answer: "de",
      explanation: "enamorarse de = sich in jemanden verlieben." },
    { id: "vp6", category: "prepositions", prompt: "casarse ___ alguien", options: ["de", "con", "a"], answer: "con",
      explanation: "casarse con = jemanden heiraten." },
    { id: "vp7", category: "prepositions", prompt: "preocuparse ___ algo", options: ["de", "por", "en"], answer: "por",
      explanation: "preocuparse por = sich um etwas sorgen." },
    { id: "vp8", category: "prepositions", prompt: "tratarse ___ algo", options: ["en", "de", "por"], answer: "de",
      explanation: "tratarse de = sich um etwas handeln." },
    { id: "vp9", category: "prepositions", prompt: "confiar ___ alguien", options: ["en", "de", "con"], answer: "en",
      explanation: "confiar en = jemandem vertrauen." },
    { id: "vp10", category: "prepositions", prompt: "acordarse ___ algo", options: ["en", "de", "con"], answer: "de",
      explanation: "acordarse de = sich an etwas erinnern." },
    { id: "vp11", category: "prepositions", prompt: "quedar ___ alguien", options: ["con", "de", "en"], answer: "con",
      explanation: "quedar con = sich mit jemandem verabreden." },
    { id: "vp12", category: "prepositions", prompt: "insistir ___ algo", options: ["en", "de", "a"], answer: "en",
      explanation: "insistir en = auf etwas bestehen." },
    { id: "vp13", category: "prepositions", prompt: "alegrarse ___ algo", options: ["en", "de", "por"], answer: "de",
      explanation: "alegrarse de = sich über etwas freuen." },
    { id: "vp14", category: "prepositions", prompt: "asistir ___ algo", options: ["a", "en", "de"], answer: "a",
      explanation: "asistir a = an etwas teilnehmen, etwas besuchen." },
    { id: "vp15", category: "prepositions", prompt: "compararse ___ alguien", options: ["de", "con", "en"], answer: "con",
      explanation: "compararse con = sich mit jemandem vergleichen." },
  ];

  function itemsForCategory(category) {
    return ITEMS.filter((it) => it.category === category);
  }
  function findItem(id) {
    return ITEMS.find((it) => it.id === id);
  }

  const CATEGORIES = Object.keys(CATEGORY_LABELS);

  return { CATEGORIES, CATEGORY_LABELS, CATEGORY_EXPLANATIONS, ITEMS, itemsForCategory, findItem };
})();
